SFTtech/openage

py/openage/convert/util.py

Real world case: empires2_x1.dat has a string `b'M\x00\xf8\x004"\xf8\x00\x00\x00\x00\x00\x00'` for one of the graphic `name1`s, which has a bunch of garbage after its terminator. `data.decode('utf-8')` trips up on this because `\xf8` is not a valid unicode char.
This patches `zstr` to truncate data to right before the first \0, or to keep it entirely if there is no \0, before utf8-decoding it.
Thanks to rkreis on #sfttech IRC for the report & patch hint :)

convert: fixes strings with garbage data past their \0 terminators

---

py/openage/codecompliance/legal.py

The compliance checker printed only the first digit of the expected year when one of the copyright years in the legal header was wrong. This should now work correctly.
Also the "from git history" part still assumed that the topmost git log entry is the most recent one (this is no longer true when someone swaps commits during a rebase, see Jonas' previous commit on that file). I deleted that part since I didn't come up with an easy fix immediately (and I don't think it is useful, just use git log if there are problems).

codecompliance: fixed error messages for legal header copyright years

---

copying.md
cpp/engine.cpp
cpp/engine.h
cpp/game_main.cpp

This is a simple refactor which points to standarize the way
to access to engine camera. For instance, scrolling with keyboard
arrows and mouse middle button was modificated to call this single
method instead of have duplicated code.

Add a move physics camera in Engine class.

---

cpp/crossplatform/os.cpp
cpp/crossplatform/subprocess.cpp

While Clang/LLVM, GCC, and Portland Group compilers define a lot of WIN32 and WIN64 macros with various numbers of underscores, the only macros that matter are those that are compatible with Microsoft's Visual Studio: _WIN32 and _WIN64.
http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#WindowsCygwinnonPOSIXandMinGW

crossplatform: use _WIN32 instead of WIN32

---

buildsystem/modules/FindOpusfile.cmake
copying.md
cpp/CMakeLists.txt
cpp/audio/dynamic_loader.h
cpp/audio/in_memory_loader.cpp
cpp/audio/types.h

improves portability of the opus location, resubmit of #212.
Probably still works for fedora (#164), somebody could test it if we're in doubt.

find opusfile via cmake, improved edition™

---

py/openage/convert/gamedata/graphic.py

fixes wrong start offset for delta graphic definitions.

delta graphics offset fixed

---

cpp/crossplatform/math_constants.h
cpp/unit/unit.cpp

This introduces namespaced math constants available on all plattforms.
closes #208.

crossplattform: enable math constants on all plattforms

---

cpp/unit/ability.cpp
cpp/unit/action.cpp
cpp/unit/action.h
cpp/unit/producer.cpp
cpp/unit/producer.h
cpp/unit/selection.cpp
cpp/unit/unit.cpp
cpp/unit/unit.h

Decaying units face correct direction and disappear after a short time.
Im not sure how the original engine knows which units decay based on gamedata, so it will just check for unit names ending in "_D" for now.

Fix decaying units

---

.travis.yml
Makefile

Currently, the sanity check is done before compiling, but the build doesn't abort if something is wrong.
That way, the error messages get burried before all the compilation output.
With this, Travis won't compile if checkfull fails.
Also, fancier IRC notification.

Abort on checkfull fail

---

copying.md
py/openage/convert/mediafile.py

`gamedata.drs` does not exist in HD edition, but the Voobly compability patch
adds an empty file. So also check that the file is not empty.

Ignore empty gamedata.drs

---

buildsystem/doxygen.cmake
copying.md

Some warnings, but you can proceed.
```
$ ./configure --mode=debug --compiler=gnu
...
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
CMake Warning at buildsystem/doxygen.cmake:49 (message):
doxygen couldn't be found, you won't be able to generate docs
Call Stack (most recent call first):
CMakeLists.txt:64 (doxygen_configure)
...
```
now:
```
$ make doc
make --no-print-directory -C bin doc
When you configured openage, Doxygen could not be found.
Install Doxygen and `./configure` openage again, then try to generate docs.
Built target doc
$ 
```
before:
```
$ make doc
make --no-print-directory -C bin doc
make[1]: *** No rule to make target 'doc'.  Stop.
Makefile:73: recipe for target 'doc' failed
make: *** [doc] Error 2
$ 
```

Add a CMake 'doc' target that explains why doc generation won't work.

---

README.md
copying.md
doc/README.md
doc/building.md
doc/implementation/convert/README.md
doc/implementation/project_structure.md
doc/media/gamedata.md
doc/media/terrain.md
doc/tasks.md

Half of the URLs in the `doc` folder gave 404 errors because they added a relative `doc/` while already in the `doc` folder.
To keep things consistent (and to avoid this error in the future), I changed such URLs to a absolute path like `/doc/usage.md`.

Doc cleanup

---

copying.md
cpp/args.cpp
cpp/main.cpp

- Fixed crashes for missing arguments
- Added shorthand `-v` for `--version`
- Added shorthand `-l` for `--list-tests`
- Added some comments for clarity
Fixes #282

Issue 282: fixed argument parser

---

cpp/game_main.cpp
cpp/game_main.h
cpp/keybinds/keybind_manager.cpp
cpp/keybinds/keybind_manager.h

Keybinds (#284) were influenced by keys like caps lock and num lock, and stopped working if one of those keys was active. That's fixed now.
I've also moved the modifier stuff from `GameMain` to `KeybindManager`, to keep things organized.

Fixed keybind modifiers

---

cpp/terrain/terrain_object.cpp
cpp/terrain/terrain_object.h
cpp/unit/action.cpp
cpp/unit/attribute.h
cpp/unit/producer.cpp
cpp/unit/producer.h
cpp/unit/unit.h

Objects like the TC were not able to be built as the foundation got removed instantly (floating outlines for buildings get removed when a building begins construction, here the annex caused the TC to remove itself)
The TC has several stages wrt collisions, the floating stage causes no collisions, the construction stage allows no units on the foundation, and once completed construction parts of the tc are able to be walked over, this is now working.
Since the change to unique_ptr<TerrainObject> in Unit, the annex objects are not cleaned up (memleak), The solution is to allow TerrainObjects to also be owned by another TerrainObject, the make annex function is moved from Unit to TerrainObject. Deletion of the parent object will now cleanup all children.

Fix annexed buildings

---

cpp/unit/producer.cpp

currently the building outline does not appear on elected buildings

show building outlines on selected buildings

---

buildsystem/python.cmake

In general it is a bad idea to place user input in a regular expression for similar reasons as sql injection. In this case the open build system places the full package name in path which in my case includes a plus (+).
```
/home/abuild/rpmbuild/BUILD/openage-v0.3.0+git20150728.5eccd7e/libopenage/main.h
/home/abuild/rpmbuild/BUILD/openage-v0.3.0+git20150728.5eccd7e/libopenage/.*\.h$
```
The plus is interpreted as a modifier for the 0 which is fine since it finds one or more zeros, but after that it looks for 'g' and instead finds '+'.
Since the only thing being checked is that the path file name ends with `.h` that is all that should be checked.

Remove user input (file path) from regular expression extension check.

---

dist/openage.desktop

Since the new python interface no longer provides this option it needs to be removed.

Remove --data=assets from .desktop file command.

---

libopenage/job/worker.cpp
libopenage/job/worker.h

This pull request removes a deadlock when stopping the worker-threads of the JobManager.

Remove deadlock in JobManager/Worker

---

copying.md
openage/convert/driver.py
openage/convert/hdlanguagefile.py
openage/convert/main.py

I know that Miguellissimo already made a pull request for fixing the bugs of the new asset system on HD (#338), but I was working on the same thing, and fixed it up so it works on my end. It would be good if someone with *regular* AoC could check if it worked on their end.
The changes are, as in the commit message:
* Conditional mounting of resource drs files/directories
* Conditional selection of palette file path (due to change in HD name)
* Makes sure directory are not added to `files_to_convert`
* New file paths for HD language files
* HD language files are decoded as utf-8

Media conversion fix for HD version 4.0

---

.mailmap
copying.md
openage/convert/driver.py

Fixed a bug where checking for the AOE2 HD version would always return true, leading to failed conversion of the original AOE2 game files.

convert: fixed checking for hd version availability

---

copying.md
libopenage/console/buf.cpp
libopenage/console/buf.h
libopenage/console/console.cpp
libopenage/util/unicode.cpp
libopenage/util/unicode.h

Supports UTF-8 characters and line-wrapping just fine.

in-game console UTF-8 backspace support

---

buildsystem/modules/FindPython.cmake
buildsystem/python.cmake
copying.md

This is a proposed fix for issue #379, in which the python library could not be found by the linker. Now we are grabbing the correct library directory using distutils, and also generating the library name the same way as the python-config tool. These are then given to the linker with -L and -l, respectively.
In the future, we should use the python-config tool to grab all ldflags and cflags. I currently don't use the python-config tool because it can include many flags (e.g, extra libraries) that we simply aren't ready to incorporate yet, and therefore would require much filtering. Since this is not currently a problem, it's a feature, not a bug.
I tested the fix on:
Mac OS X Yosemite 10.10.4 (14E46)
Python 3.4 installed with brew install python3
Using g++ version 5.2.0
and
Ubuntu 14.0.4-3 …

Include -L<dir> flag for linking against python

---

doc/building.md

Cython and Pygments are required, but not listed under the list of dependencies to install for Arch Linux.

Added missing dependency under Arch Linux

---

buildsystem/cpp.cmake
doc/building.md
libopenage/game_control.cpp
libopenage/input/event.h
libopenage/util/compiler.h
libopenage/util/profiler.h

This is a proposed fix for issue #382. In order to build openage on Mac, clang 3.5 or higher should be installed through Homebrew. I have updated building.md (increase clang version, add extra Homebrew and Mac OS X instructions) and made minor modifications to source files to support clang on Mac.

Change code (and documentation) to support clang on Mac OS X.

---

copying.md
libopenage/unit/unit.cpp
libopenage/unit/unit.h

Fixes #386  - when the user moves a villager away from gathering a resource the villager will not go back to collecting it.

Villagers stop gathering resources

---

libopenage/unit/ability.cpp
libopenage/unit/action.cpp
libopenage/unit/action.h
libopenage/unit/attribute.h
libopenage/unit/producer.cpp
libopenage/unit/producer.h
libopenage/unit/resource.h

I am working on the issue #377.

Villagers bring their resources to the correct buildings

---

CMakeLists.txt

distros may have their own build type, e.g. Gentoo

buildsystem: don't enforce release or debug

---

copying.md
doc/code/convert/README.md
openage/convert/CMakeLists.txt
openage/convert/driver.py
openage/convert/game_versions.py
openage/convert/main.py

Introduce GameVersion enum, and store an instance once determined.
Everybody else can switch version-specific code upon it, instead of
reinventing the wheel
I'm using [enum](https://docs.python.org/3.4/library/enum.html), which is available as of python 3.4 - didn't find a note how backwards compatible you want to be.

convert: Check for game version in only one place

---

assets/shaders/alphamask.frag.glsl
assets/shaders/alphamask.vert.glsl
assets/shaders/equalsEpsilon.glsl
assets/shaders/maptexture.frag.glsl
assets/shaders/maptexture.vert.glsl
assets/shaders/teamcolors.frag.glsl
assets/shaders/texturefont.frag.glsl
assets/shaders/texturefont.vert.glsl
copying.md
libopenage/game_renderer.cpp
libopenage/shader/shader.cpp
libopenage/shader/shader.h

+ Made the number of possible player colors variable (assets/converted/player_palette.docx)
+ Simplified equals with epsilon checks
+ Introduces a way to share common functions between shaders
+ Shader constructor takes a list of shader code snippets instead of on code char array
+ removed shader header from shaders.
+ add equalsEpsilon.glsl as first shared shader code.
+ game_renderer derives number of player colors from player_color_lines

Improvments of the team colors shader

---

copying.md
libopenage/unit/action.cpp

Civilian where taking theirs idle sprite even when holding resources.
Since the carrying sprite is walking, we have to stop the frame update when it happened.
It's my first contribution, and I have some difficulties with git, so I've made just a tiny commit for the first time.

Fix: Civilian holding ressources when idled

---

openage/convert/singlefile.py

this is required until the buildsystem detects that slp is
provided by a .py file as well.
otherwise, it is calculated that the slp...so file is required for
creating all the .so files, which is a dependency loop.
this loop doesn't exist as the slp...so is just a compiled version of
slp.py.

convert: don't include slp in singlefile root

---

buildsystem/modules/FindPython.cmake

Use proper config_var for determining the python library directory.

buildsystem: fix python library dir finding

---

openage/convert/driver.py
openage/convert/game_versions.py
openage/convert/hdlanguagefile.py
openage/convert/main.py

HD Edition 3.x puts language files in a slightly different place,
and uses a funny encoding for them (i.e. not utf-8).
(At least, a funny encoding for the English language files. I'm
_assuming_ that it's the same for other languages.)
Otherwise it's largely the same as non-HD.
There are some additional SLP files in the `Data/Slp` directory,
apparently dealing with UI and fires too(?). There are some extra
palette files in the `Data/` directory too but I'm not sure how they
are mapped to their relevant SLP files.
e; now with copyright years :muscle:

convert: support HD Edition 3.x, fixes #444

---

copying.md
libopenage/game_renderer.cpp
libopenage/input/input_context.cpp

I had a build error w/ sstream header missing, fixed:
```
/Users/user/git/openage/libopenage/input/input_context.cpp:15:21: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char,
std::__1::char_traits<char>, std::__1::allocator<char> >'
std::stringstream ss;
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:126:33: note: template is declared here
class _LIBCPP_TYPE_VIS_ONLY basic_stringstream;
```

fix build on mac os mavericks

---

libopenage/error/error.h

errors lead to crashes anyway, so the collection doesn't impact performance of a crashed program :)

error: enable backtrace collection by default

---

.mailmap
copying.md
openage/convert/driver.py

Thanks @goto-bus-stop! Your suggested fix works.
---
Forgotten Empires uses plaintext files for language strings. There may
still be files from older versions, but with unexpected contents.
Also see #462.

Prefer plain text over language.dll (fixes #461)

---

openage/convert/texture.py

Directly use numpy arrays instead of building and looping through
Python lists.

Optimize texture frame merging

---

copying.md
libopenage/log/message.cpp

Won't this init() interleave when multiple threads enter the function?
The potential result would be the wrong thread_id paired with the wrong timestamp.
Moving the guard up would mitigate it.

Expanded the critical section to include init()

---

openage/convert/CMakeLists.txt
openage/convert/binpack.py
openage/convert/hardcoded/CMakeLists.txt
openage/convert/hardcoded/texture.py
openage/convert/texture.py

An implementation of texture packing, see #314. **Code review and comments welcome.**
---
Results:
```
Strategy                                              | Total pixels |   %
------------------------------------------------------+--------------+----
Checkerboard (current state)                          | 350 244 210  | 100
Binary tree packer (target aspect ratio: 1)           | 220 296 651  |  63
Naive stripe with one row                             | 216 087 516  |  62
Binary tree packer (target aspect ratio: 1 or 97/49)  | 213 799 289  |  61
Combined                                              | 202 956 009  |  58
```
---
Example images from combined result:
(Single stripe)
(Binary tree aspect ratio 1)
(Binary tree aspect ratio 97/49)
---
Sum up number of pixels in all PNG files: …

texture bin packing improvements

---

copying.md
libopenage/unit/action.cpp

When switching to different resource type for gathering, reset the amount already gathered. Fixed #364

Reset the amount gathered upon switching resource type

---

libopenage/crossplatform/signal.h

WIN32 needs it as well as APPLE

crossplatform/signal: typedef sighandler_t for WIN32

---

copying.md
openage/convert/driver.py

Added support for HD Edition 2.0, where string data is in DLLs in PATH/Data/LANG/*.dll
This might be better done by detecting that version explicitly, rather than checking for DLLs in the languages folder, but this works for now.
Prior to this fix, the importer would try to read the .dlls as text files, resulting in the following error:
Traceback (most recent call last):
File "run.py", line 15, in <module>
main()
File "/home/archie/openage/openage/__main__.py", line 94, in main
return args.entrypoint(args, cli.error)
File "/home/archie/openage/openage/game/main.py", line 33, in main
if not convert_assets(assets, args):
File "/home/archie/openage/openage/convert/main.py", line 125, in convert_assets
for current_item in convert(args):
File "/home/archie/openage/openage/convert/driver.py", …

Added support for importing string data from HD 2.0

---

libopenage/game_control.cpp

Title says it already. I am not sure if the implementation with CTRL is intended, but the original game uses SHIFT so I fixed it that way.

Do append selection with SHIFT key instead of CTRL

---

CMakeLists.txt
buildsystem/HandleCXXOptions.cmake
buildsystem/compilepy.py
buildsystem/modules/FindPython.cmake
buildsystem/modules/FindSDL2.cmake
buildsystem/python.cmake
buildsystem/util.cmake
configure
libopenage/CMakeLists.txt
libopenage/renderer/font/font.cpp
libopenage/util/stringformatter.cpp
libopenage/util/stringformatter.h
openage/CMakeLists.txt

* Mainly fixes the devmode installation.
* Python files are now compiled by a python script and not by `compileall`
* the `configure` script is now pylint compliant
* We no longer need a c compiler (I hope it's not just because of my cmake `>=3.4.0`)
* ok, i was wrong. but i "fixed" it by reusing cxx as the c compiler if cmake is `<3.4.0`
* Compiler flags are no longer duplicated
* 2 random warning fixes for move-optimization and atomic_flag initialization

Buildsystem improvements, once again

---

buildsystem/doxygen.cmake
copying.md

If a parent directory of openage contains a space, 'make doc' (or better, doxygen)
splits the absolute path from the INPUT tag in bin/Doxygen in two directorys.
That way, the necessary files cannot be found and no documentation is created.
This commit adds quotation marks to the responsible cmake file.
geändert:               buildsystem/doxygen.cmake

fixes documentation issue #511

---

copying.md
openage/convert/CMakeLists.txt
openage/convert/driver.py
openage/convert/hardcoded/texture.py
openage/convert/interface/CMakeLists.txt
openage/convert/interface/__init__.py
openage/convert/interface/interfacecutter.py
openage/convert/interface/interfacehardcoded.py
openage/convert/interface/interfacerename.py
openage/convert/interface/visgrep.py
openage/convert/slp_converter_pool.py
openage/convert/texture.py

There are 1280x1024 backgrounds currently extractable from the AOC game data (if interface.dat is enabled in the conversion script). No subtextures defined.
1. For the ingame HUD: I'm going to manually specify the coordinates of the bottom rectangles that are in the corners.
2. For the top stripe of the ingame HUDs it's possible to detect a repeating pattern and get coordinates of a good piece. I've ported a `visgrep` utility from xautomation to python. It does the pattern search without having something like OpenCV or GIMP as a dependency.
Middle-bottom part of the HUD - that should be probably generated at runtime because the aspect ratio is dynamic. So, it's not a part of this PR.
For the first push there is only the `visgrep.py` utility.
If someone can confirm that we can't extract …

GUI ingame background assets adaptation (AOC/HD)

---

doc/media/gamedata-struct.md

References #513. Updating the documentation in `gamedata-struct.md` to reflect the current implementation in the `openage/convert/gamedata` directory.
Resubmit of #521.

Documentation updates to gamedata structs

---

doc/reverse_engineering/damage.md

Missing enumeration for attack and armor classes made them show up in a single line.

doc: fix enumeration in damage calculation notes

---

doc/code/pyinterface.md

Because, I keep forgetting it.

[doc-fix] adding the missing call to call in the cpp example

---

libopenage/game_control.cpp
libopenage/terrain/terrain_object.cpp
libopenage/unit/action.cpp
libopenage/unit/action.h
libopenage/unit/command.h
libopenage/unit/selection.cpp
libopenage/unit/unit.cpp
libopenage/unit/unit.h

Replace `unit.invoke(Command &)` with `unit.queue_cmd(Command &)` which queues commands to be applied at the next update. queue_cmd is safe to call from multiple threads.
Building placement is fixed, as described in https://github.com/SFTtech/openage/issues/535
Also fixed an issue where gatherers would only return wood.

Command queue, and fix building placement segfault

---

copying.md
libopenage/unit/ability.cpp
libopenage/unit/command.h
libopenage/unit/unit.h

Cleanup of some include calls. Fixes #541.
Tested with current osx clang, osx g++ 5.3 (brew) as well as clang 3.5 and g++ 4.9.2 (both debian jessie).

Fixed osx clang compile errors.

---

copying.md
doc/building.md
libopenage/CMakeLists.txt
libopenage/renderer/font/font.cpp

Fixes compile error on OS X with clang 3.8 in debug mode.
Other things we need to take care of if we require a newer harfbuzz version?

Require harfbuzz version >= 1.x.x

---

.mailmap
README.md
copying.md
doc/nyan/conversion.md
doc/nyan/examples.md
doc/nyan/nyan.md
doc/nyan/openage-lib.md
libopenage/terrain/terrain_object.cpp

This adds some documentation about our usage of nyan.
The documentation of nyan itself is in the nyan project repo, this is just about the openage specifics.

Documentation for openage nyan usage

---

.mailmap
openage/convert/main.py

When an empty string is entered, `expand_relative_path` returns the current directory, so the `not new_wineprefix` check would always fail. This checks the input first before passing it to `expand_relative_path`.

convert: fix check for empty WINEPREFIX input, fixes #558

---

copying.md
libopenage/unit/unit_texture.cpp

Fixed the issue #554 .
This issue applies only to (Mill, Mining camp and Lumber camp), other buildings preview color is determined by [this line](https://github.com/SFTtech/openage/blob/cb0afc9a29451ccb3efdd14e5103038a5c726276/libopenage/unit/unit_texture.cpp#L54).

Show the color of the active player in buildings preview

---

copying.md
libopenage/game_control.cpp
libopenage/game_control.h

Fixes #531.
When ending the game the selection doesn't get cleared, so changing to Action Mode after starting a new game will call `selection.clear()` which tries to access selected units from previous game.
My fix is to call `selection.clear()` when leaving the Action Mode so that the current selection will be cleared before ending the game.

Clear the selection after exiting the ActionMode instead of after entering it

---

buildsystem/pxdgen.py
buildsystem/python.cmake

previously, a single pxdgen input header change triggered
the retouch of every possible generated pxd output file.
this triggered the recompile of every pyx file,
so the python .so files were compiled every time.
hnng buh-buuh.

buildsystem: fixed pxdgen output regeneration

---

copying.md
libopenage/engine.cpp
libopenage/engine.h
libopenage/game_control.cpp
libopenage/game_control.h

Keep unit selections when switching game mode or menu

---

CMakeLists.txt
buildsystem/HandleCXXOptions.cmake
doc/building.md

possibly fixes #590
it's a bit dirtier than before, because the flags are now:
```
(...)  -std=c++14 (.....) -g -Og -fPIC   -fPIC -std=gnu++14 -o (....)
```
If I remove the first `std=`, the compilations done in the configuration fail. And the second one seems to be unchangable from `gnu++14` to `c++14`.

buildsystem: set cxx_standard to fix qt bug

---

cfg/keybinds.oac

ESC should just be the key to cancel things like building placement etc., pressing it to find the game closed is annoying 😄

config: rebind STOP_GAME to Shift+ESCAPE

---

libopenage/unit/action.cpp

Currently, when completing a building it will usually display as a little bit more than 1.0 completed. This just sets the `completed` property to `1.0f` when the building is fully completed.

Limit building completion to 1.0

---

libopenage/engine.cpp
libopenage/engine.h
libopenage/error/CMakeLists.txt
libopenage/error/gl_debug.cpp
libopenage/error/gl_debug.h
libopenage/main.cpp
libopenage/main.h
openage/game/main.py
openage/game/main_cpp.pyx

A `--gl-debug` option that creates a debug context instead of a normal one. Gets a more precise backtrace when error occurs.

GL debug option

---

buildsystem/codecompliance/__main__.py
buildsystem/codecompliance/pylint.py

the linting part of `make checkall` used to run
import subprocess
subprocess.call(['pylint'] + args)
Now, it is invoked via
import pylint.lint
pylint.lint.Run(args)

codecompliance: pylint is now imported, not invoked

---

openage/util/fslike/union.py

Due to an off-by-one error in `Union.add_mount()`, new mounts overlay the lowest mount, that had a _higher_ priority than the new one. This bug becomes really critical, when the new mount has a priority higher than any other mount. In this case the new mount is inserted at index '-1' (it becomes the second last mount), and not at '0'.
To test this with your own eyes, execute the *.sh once and then unionbug.py (read the in-source comment). 
https://github.com/castilma/openage/blob/unionbug/preptest.sh
https://github.com/castilma/openage/blob/unionbug/unionbug.py
edit: I wonder if the overlapping feature from Union is even used by the convert script. Or why didn't we notice this? This bug is over 2 years old. I found it while reading the source, trying to understand how Union works.

util: fixes wrong priority handling in Union

---

libopenage/gui/guisys/link/gui_item.h
libopenage/gui/guisys/link/gui_item_link.h

Unwrapping of the GUI binding classes like `SomeClassLink` into `SomeClass` uses type trait `Unwrap` that is defined in the header with corresponding type. If the header is not included, then compiler considers it as a basic type and tries to pass it wrapped to a function that expects an unwrapped type. To warn about that possibility, PR adds a compile-time error message if the arguments don't match for any reason.

GUI: Warn about possible missing includes

---

buildsystem/codecompliance/__main__.py
buildsystem/codecompliance/pystyle.py
doc/building.md
openage/__main__.py

The pep8 module was renamed to pycodestyle:
https://github.com/PyCQA/pycodestyle
https://github.com/PyCQA/pycodestyle/issues/466

pep8 module renaming support

---

libopenage/game_control.cpp
libopenage/game_control.h
libopenage/gui/game_control_link.cpp
libopenage/gui/game_control_link.h
libopenage/gui/qml/CreateGameWhenReady.qml
libopenage/gui/qml/main.qml

Checkbox to generate the game and enter the ActionMode as soon as the assets are loaded.
Related to #551: click on the checkbox once instead of clicking the generate_game until it loads.
For more specific stuff it's probably useful to figure out how to write demos (like a demo to record replay and a demo to play it). But the autolaunch feature looks generic enough to be added to the generator's menu.

GUI: Start game after assets have loaded

---

libopenage/gamestate/CMakeLists.txt
libopenage/gamestate/game_main.cpp
libopenage/gamestate/game_main.h
libopenage/gamestate/player.cpp
libopenage/gamestate/player.h
libopenage/gamestate/team.cpp
libopenage/gamestate/team.h

Added teams of players. Member types are also supported, currently we have:
- leader: creator and master of the team
- member: member before the start of the game
- recruit: player that became member at some point during the game
I cant understand what that means (need help):
```
.../openage$ make checkall
python3 -m buildsystem.codecompliance --all
************* Module openage.__main__
W: 60, 4: Reimport 'init_subparser' (imported line 54) (reimported)
W: 65, 4: Reimport 'init_subparser' (imported line 54) (reimported)
W: 70, 4: Reimport 'init_subparser' (imported line 54) (reimported)
W: 75, 4: Reimport 'init_subparser' (imported line 54) (reimported)
WARNING linting issue: python code is noncompliant: 4
Makefile:126: recipe for target 'checkall' failed
make: *** [checkall] Error 1
```

Player teams

---

libopenage/terrain/terrain_search.cpp
libopenage/terrain/terrain_search.h
libopenage/unit/action.cpp
libopenage/unit/action.h
libopenage/unit/unit.cpp
libopenage/unit/unit.h

When a unit's current action is to build a building and that building
completes, it will now search for the closest building and then queue
building that.
~~Currently, there are no range limitations as explained in
doc/reverse_engineering/building_placement.md and it's horribly
inefficient (it searches through ALL units on the map).~~

Keep building after finishing a building

---

doc/reverse_engineering/repair.md
libopenage/game_control.cpp
libopenage/gamestate/CMakeLists.txt
libopenage/gamestate/generator.cpp
libopenage/gamestate/player.cpp
libopenage/gamestate/player.h
libopenage/gamestate/resource.cpp
libopenage/gamestate/resource.h
libopenage/gui/actions_list_model.cpp
libopenage/unit/ability.cpp
libopenage/unit/ability.h
libopenage/unit/action.cpp
libopenage/unit/action.h
libopenage/unit/producer.cpp

Repair of units based on the [doc/reverse_engineering/repair.md](doc/reverse_engineering/repair.md) (file in pull request).
In order to continue:
* ~~A data structure for multiple resource costs should be implemented (game_resource_bundle ?)~~
* The cost of the unit should be stored somewhere (inside unt_type ?)
~~Can I implement these? or just leave as it is and revisit after the nyan revolution?~~
EDIT: Also game_resource_bundle should replace the `game_resource type, int value` couples all over the place.

Repair action & resource bundle

---

copying.md
libopenage/CMakeLists.txt
libopenage/gui/guisys/public/gui_renderer.h

This is basically the patch-only part of #658 which seems to fix the build at least.
Fixes #653
Fixes #643

buildsystem: add includes for qt5 on macOS

---

assets/.gitignore
libopenage/gamestate/game_spec.cpp
libopenage/gamestate/game_spec.h
libopenage/main.cpp
libopenage/util/file.cpp
libopenage/util/file.h
libopenage/util/timer.cpp
openage/convert/changelog.py
openage/convert/dataformat/data_definition.py
openage/convert/dataformat/data_formatter.py
openage/convert/dataformat/generated_file.py
openage/convert/dataformat/members.py
openage/convert/dataformat/struct_definition.py
openage/convert/dataformat/util.py
openage/convert/driver.py
openage/convert/slp_converter_pool.py

From
to
(after the first time)
I create a `cache.docx` file which contains all the other `*.docx`. Every time the read csv function is called the the file is added to the cache file. The first time (before the creation of the cache) the load time is like the old days and from the second time and after all the loading is happening from the cache structure much faster (= 34 times faster).
- The cache file is only around 13 MB
- Fixed the timers wrong logic
- Comments are not cached

Load data 34 times faster!

---

buildsystem/modules/FindGCCBacktrace.cmake
libopenage/CMakeLists.txt
libopenage/error/demo.cpp
libopenage/error/error.h
libopenage/game_control.cpp
libopenage/gamestate/civilisation.cpp
libopenage/gamestate/game_main.cpp
libopenage/gamestate/game_spec.cpp
libopenage/gamestate/generator.cpp
libopenage/gamestate/player.cpp
libopenage/gui/actions_list_model.cpp
libopenage/gui/integration/private/gui_log.cpp
libopenage/input/text_to_event.cpp
libopenage/log/log.h
libopenage/log/named_logsource.h
libopenage/main.cpp
libopenage/pyinterface/exctranslate_tests.cpp
libopenage/renderer/font/font_manager.cpp
libopenage/screenshot.cpp
libopenage/unit/selection.cpp
libopenage/unit/unit.h
libopenage/unit/unit_container.cpp
libopenage/unit/unit_container.h
libopenage/unit/unit_texture.cpp
libopenage/util/externalprofiler.cpp
libopenage/util/file.cpp
libopenage/util/os.cpp
libopenage/util/subprocess.cpp

* Fixed linker error when building with libbacktrace.
* `log/log.h` was implicitly imported by `error/error.h`.
* Reordered some includes to match "associated - global - local" structure.

fix build with libbacktrace, clean up log includes

---

.kevin

SFTtech/kevin#14. For the time being, this should be an acceptable workaround.

force colored cmake output in kevin builds

---

buildsystem/codecompliance/__main__.py
buildsystem/codecompliance/pylint.py

pylint crashes in multiprocessing mode when there are compiled cython modules in the tree (despite explicitly ignoring those modules). We have to fall back to single-process mode in this case.
Otherwise, this speeds up the style checker by about 10 seconds. Would be pretty nice for kevin builds.
Also fixed a bug where you could not run the codecompliance module in textfile only mode.

use multiprocessing with pylint

---

.kevin

We have a new server with a lot of processing power. CI can now run with 24 cores instead of 4. Timers are now down to 13 sec for codestyle and 50 sec for build. :tada: :fireworks:

run ci with 24 cores

---

libopenage/audio/audio_manager.cpp

C++ is awesome. `device_spec.channels` is a `uint8_t` and therefore printed as `char`.

audio: fix broken log message

---

doc/building.md
libopenage/gui/guisys/private/gui_application_impl.cpp
libopenage/gui/integration/private/gui_log.cpp

Qt 5.5 has introduced the INFO log level that fits for the version printing.

Log Qt version and bump to Qt 5.5

---

libopenage/CMakeLists.txt

Follow-up to #726 where we forgot to bump it in the buildsystem.

buildsystem: require >=Qt-5.5

---

libopenage/gamestate/resource.cpp
libopenage/gamestate/resource.h
libopenage/unit/CMakeLists.txt
libopenage/unit/ability.cpp
libopenage/unit/action.cpp
libopenage/unit/action.h
libopenage/unit/attribute.cpp
libopenage/unit/attribute.h
libopenage/unit/attributes.cpp
libopenage/unit/attributes.h
libopenage/unit/producer.cpp
libopenage/unit/selection.cpp
libopenage/unit/unit.cpp
libopenage/unit/unit.h
libopenage/unit/unit_type.cpp
libopenage/unit/unit_type.h

- All files including `attributes.h`: `unit_type.h`, `unit.h`, `action.h`
- `Attributes` methods:
- bool add/has/removeAttribute (hide all map methods)
- Attribute get<attr_type>
- Health reset every time villager changes resources (eg. from wood to stone) (wait... no)
- One gather rate for all resources
- Search for new building to build includes enemy's building
- Towers auto attack
- ...

Attributes system improvements

---

libopenage/unit/action.cpp

Fix to #760. Some projectile do not have owners, added checks for that.
In the future (when the friendly fire and accuracy is (re)implemented) this should be revisited.
EDIT: the `active_unit_removed` and `active_unit_added` are reworked in #758.
EDIT2: also now the kill cannot be credited to a player

Bug fix: Ownerless projectiles

---

CMakeLists.txt
buildsystem/doxygen_custom.css
buildsystem/templates/Doxyfile.in

I don't know if the custom css should have only the overrides I want or if I should copy the entire doxygen stylesheet and do modifications there.
Screenshot:
References: #180

Doxygen improvements

---

copying.md
libopenage/engine.cpp

- This allows to stop all workers
- after that is done the exception is rethrown
fixes #766

Surrounded Engine::run with try catch

---

libopenage/rng/rng.cpp
libopenage/util/hash_test.cpp

See here for more info: https://stackoverflow.com/questions/14794490/c-stdarray-warning
For some reason my clang kept complaining about `a = {stuff}`, so I went with `a {{stuff}}`.

fix missing braces warnings for subobject initialization

---

buildsystem/codecompliance/authors.py
copying.md

Enable contributors to obfuscate the email address they publish in `copying.md`.
Main goal here is to make it less of a target for search engines.

Obfuscate email addresses in `copying.md`

---

openage/convert/hdlanguagefile.py

I did `make run` for the first time, and found that the search for string resources looks in the wrong path. It looks in `resources/resources/`. As a result: no string resources are found, and `driver.py` reaches [this statement](https://github.com/SFTtech/openage/blob/6488818ff0412f5e7f1df7a1af724b79decf657f/openage/convert/driver.py#L54):
```python
if not count:
raise FileNotFoundError("could not find any language files")
```
I assume this is because [`driver.py` sets `path` to `srcdir["resources"]`](https://github.com/SFTtech/openage/blob/6488818ff0412f5e7f1df7a1af724b79decf657f/openage/convert/driver.py#L41), so when `hdlanguagefile.py` adds another `"resources"` into the search path: it fails (there's no such directory as `resources/resources`).
Maybe the better place to make this …

Fix Age2HD string resources search

---

libopenage/texture.cpp

Fix pixel transfer format for loading an OpenGL texture from an SDL surface. On Mac, this swaps the red & blue channels (so RGB becomes BGR).
Before:
After:
Basically I just copied [this stackoverflow](http://stackoverflow.com/a/4340330/5257399).

Fix RGB endianness used in pixel transfer

---

buildsystem/modules/FindPython.cmake

fixes #793 by allowing a number at pythontex.

Buildsystem: blacklisting pythontex more flexible

---

.kevin

This improves the dirty workaround introduced by #700. Kevin now supports control-file conditionals :)

kevin: don't run sanity check on debian

---

libopenage/testing/CMakeLists.txt
libopenage/testing/benchmark_test.cpp
openage/codegen/cpp_testlist.py
openage/testing/CMakeLists.txt
openage/testing/benchmark.py
openage/testing/list_processor.py
openage/testing/main.py
openage/testing/testlist.py

fixes #167
added ```./run test -b BENCHMARK ``` for benchmarking the code. 
It runs the benchmark until the whole block takes longer than 5 seconds, totalling in 10 seconds for the whole process. Minimum of 7 Iterations in total.
This enables us, to benchmark also more complex systems that take a longer while, and still keep the same logic for high-performance tests.
It will produce Output like: 
```
$ ./run test -b testing.benchmark.benchmark
Iterations Total time    Average time per execution
1  0.10013296s  0.10013296s
2  0.20025852s  0.10012926s
4  0.40048001s  0.10012000s
8  0.80094380s  0.10011798s
16  1.60193363s  0.10012085s
32  3.20378083s  0.10011815s
64  6.40750377s  0.10011725s
Benchmark Results:
------------------
Iterations Total time    Average time per execution
127 …
```

Buildsystem: Added Benchmarking

---

doc/media/drs-files.md
openage/convert/driver.py
openage/convert/main.py

This adds an option to ignore AI and Random Map scripts.
Interface files where not filtered correctly. I found this by running
`$ python3 -m openage convert --no-graphics --no-interface --no-metadata  -v  --force`
There are some `bin` files belonging to animations in `interface.drs`. This documented in `doc/media/drs-file.md`.
There was no option to ignore the random map scripts. There is now.

convert: enhance filter options

---

libopenage/console/buf.cpp
libopenage/engine.cpp
libopenage/gui/guisys/private/platforms/context_extraction_x11.cpp
libopenage/util/compress/lzxd.cpp

This is not exhaustive, but remaining warnings seem to be triggered in generated code.
See https://ptpb.pw/7wcN

Fixes for GCC7

---

libopenage/gamestate/resource.cpp
libopenage/gui/guisys/CMakeLists.txt
libopenage/gui/guisys/private/gui_ctx_setup.cpp
libopenage/gui/guisys/private/gui_ctx_setup.h
libopenage/gui/guisys/private/gui_renderer_impl.cpp
libopenage/gui/guisys/private/gui_renderer_impl.h
libopenage/gui/guisys/private/gui_rendering_setup_routines.cpp
libopenage/gui/guisys/private/gui_rendering_setup_routines.h
libopenage/gui/guisys/private/opengl_debug_logger.cpp
libopenage/gui/guisys/private/opengl_debug_logger.h
libopenage/gui/guisys/private/platforms/context_extraction.h
libopenage/gui/guisys/private/platforms/context_extraction_cocoa.mm
libopenage/gui/guisys/private/platforms/context_extraction_x11.cpp

Try to init GUI as usual, fallback to the shared context mode if it fails.

GUI: Also try a separate-shared-context mode

---

libopenage/util/fslike/directory.cpp

Since we are setting time to "NOW", we can just use a nullptr. We can also ditch `time.h`, since we no longer need `clock_gettime()`.

Fix build on macOS computers that don't have Sierra && XCode 8

---

libopenage/gui/guisys/private/platforms/context_extraction_cocoa.mm
libopenage/gui/guisys/private/platforms/context_extraction_x11.cpp

By reverting the final change to gui-gl-context, Mac runtime gets a little further.
We need to mention the magic commit (d577f5681bf61e09cd7d8175661be2df389b9b4d):
```bash
git cherry-pick --no-commit d577f5681bf61e09cd7d8175661be2df389b9b4d
```
master = launches successfully with fully black window; never renders anything
master + magic commit = launches grey window, finishes loading, encounters SIGSEGV
master + this pull request + magic commit = launches window, proceeds to the graph view. successfully presents game if you click generate_game.

undo final change of gui-gl-context pull request, to prevent SIGSEGV

---

libopenage/audio/opus_loading.cpp

Found while investigating #831.

audio: remove debug leftovers for opus loading

---

copying.md
libopenage/datastructure/constexpr_map.h

This fixes type errors in the `constexpr ConstMap` structure.

Constmap fix

---

libopenage/cvar/cvar.h

Small type error (why did it work before??).

cvar: fix python type

---

copying.md
doc/reverse_engineering/civilizations.md
doc/reverse_engineering/scoring.md
doc/reverse_engineering/unit_stats/unit_stats_aoe.csv
doc/reverse_engineering/unit_stats/unit_stats_aoe.txt

This PR includes documentation regarding the original Age of Empires I
(not Rise of Rome). Rise of Rome will probably be implemented in another
PR.
The scoring system and civilization specials and unit/building creation
table are completely documented.
Feedback is appreciated regarding the formatting; I am not sure if this
is sufficient or if the documentation should be located elsewhere.

Doc - Civilization and unit statistics for AoE I

---

README.md

Fixed spelling mistake in README

---

libopenage/unit/action.cpp
libopenage/unit/action.h

Minor correction to last pr. Using the pointer to target unit in on_completion() is not a good idea, they may already be removed. Instead pass id of the type.

units can get removed before on_complete runs

---

doc/reverse_engineering/formations.md

This PR aims to summarize all results from #705 which @Piruzzolo and me have discovered. I think nobody wants to read through the lengthy discussion to get something done.

doc on Formations

---

libopenage/screenshot.cpp

the memcpy takes only 6 ms, the manual copy took 14 ms. `IMG_SavePNG` unfortunately still takes about a second. 
I adjusted the imports to match our style.

save alpha-channel in screenshots

---

libopenage/error/error.cpp
libopenage/error/error.h
openage/__main__.py
openage/convert/main.py
openage/cppinterface/exctranslate.pyx
openage/cppinterface/setup.py
openage/game/main.py
openage/testing/main.py

Implements #570  
Test this with: 
`./run test -a` will run successfully without changes
`./run test --trap-exceptions -a` will trap wit: 
```
[ 3/27]  py cppinterface.exctranslate_tests.cpp_to_py
[1]    23108 trace trap (core dumped)  ./run test --trap-exceptions -a
```

Exceptions: break into debugger on throwing an exception

---

libopenage/error/error.h
openage/cppinterface/exctranslate.pyx

Fixed cython calling static member method in C++.
http://docs.cython.org/en/latest/src/userguide/wrapping_CPlusPlus.html#static-member-method

exceptions: made cython more beautiful.

---

doc/media/drs-files.md
openage/convert/driver.py
openage/convert/drs.py
openage/convert/singlefile.py

Internally, Age of Empires does something like this when reading files
from a DRS archive:
```c
read_drs_file('bina', 50500);
```
Note how it uses a C char with multiple bytes. This is stored on disk as a
little-endian integer, so the 'a' byte ends up at the lowest address,
and the 'b' byte ends up at the highest address. Hence why it appears
to be reversed.
The "magical byte" is simply a padding space ' ' character or the final 'a' of
the "bina" file type.

doc: Update DRS file format.

---

README.md
doc/build_instructions/windows_msvc.md
doc/building.md

- Update the Windows build instructions to use more ports from vcpkg, viz. dirent, opusfile.
- Add cautionary note: qt5 is **not** fun to build/install.
- Integrate the Windows build instructions properly in the documentation.
Kindly notify me of other updates required in the documentation. I can try to address those in this PR.

Windows documentation update

---

CMakeLists.txt
configure

Speeds up some compilations if used.
The cache will be in `~/.cache/ccache` by default.
`ccache -s` will show you statistics. which you can `watch -n1` during builds :)

buildsystem: add convenience options for using ccache

---

libopenage/renderer/font/font.cpp
libopenage/renderer/font/font.h
libopenage/renderer/font/glyph_atlas.cpp

Fixes the memtype mismatch crash of #884.

renderer: fix font glyph memory allocations

---

copying.md
doc/debug.md

I figured out how to debug libopenage with gdbgui. It is a browser-based frontend to gdb built with Python and JavaScript.
gdbgui: https://github.com/cs01/gdbgui
This PR:
- Add a .gdbinit (gdb commands) to debug openage and break at main.cpp
- Document how to debug openage and how to do this with gdbgui

Support and document debugging with gdbgui

---

openage/cppinterface/exctranslate_tests.pyx
openage/testing/misc_cpp.pyx

[Reverted in favor of #895] ~Fixes #876 - verified on Windows (NTFS).~
A few modifications to assertions in existing tests to accommodate MSVC's behavior.

Get more tests to pass on Windows

---

assets/.gitignore
buildsystem/codegen.cmake
libopenage/CMakeLists.txt

Fixes #907.
Otherwise build may fail because there's
no known recipe to generate the files.
~~We should maybe tune the codegen target to actually have all the generated files as output, not just the timefile. This now was the easier fix, though.~~
The codegen custom command now knows all its output, but the codegen target still depends on the timefile only, so the command isn't run for every generated source.

buildsystem: let automoc depend on codegen

---

libopenage/util/filelike/native.cpp

Python code already does this, so match the behaviour in CPP.

Use binary mode for files in cpp

---

libopenage/engine.cpp

Removed the requirement for the mouse to be focussed in the window because it created problems in two scenarios:
1. Mouse scrolling in windowed mode is basically useless because the mouse has to be exactly on an edge for scrolling.
2. Same for a fullscreen multi monitor setup. At least one edge is unfeasible for mouse scrolling.

fix scrolling without focus (again)

---

buildsystem/pxdgen.py

A workaround until cython/cython#1912 is addressed and a fix is available.
Summary of the changes
- Both `\` and `/` are valid path separators on Windows. The first one is native and default in python (like most other applications), but requires escaping (even in raw string literals - see referenced cython issue).
- The workaround: replace all instances of the first path separator with the (lesser-used, but still acceptable) second one which works for cython without escaping.

[Windows] Change path separator in generated pxd files

---

copying.md
openage/util/system.py

I changed the function so that there is a single and clear exit point. I set memory to INF at the start to silence the linter although I would prefer it in the else branch personally.

[Refactor] util/system.py free_memory() single exit point

---

libopenage/CMakeLists.txt

the system detection 'dribble' Linux/FreeBSD

Let s just use directly the cmake variable, avoiding

---

openage/convert/dataformat/data_definition.py
openage/convert/main.py
openage/convert/slp_converter_pool.py
openage/util/decorators.py
openage/util/files.py
openage/util/fslike/union.py
openage/util/iterators.py
openage/util/struct.py

This includes and thus closes #938.

Make pylint shut up after update to 1.8.1

---

buildsystem/codecompliance/legal.py

When a PR gets merged in another year than the commits are dated,
the expected copyright year in the changed files changes to the
merge-commits year. This makes the copyright year wrong according to our
codecompliance check.
This might happen, because of a PR gets merged in a year after the last
change, or because the PR got rebased without '--ignore-date'.

codecompliance: ignore merge-commit-dates

---

CMakeLists.txt

Possible fix for #968.
* Need to test on second machine. @benapetr, @zuntrax: please give this a try.

Compiler features check failure for VS 2017

---

openage/convert/opus/opusenc.pyx

I somehow used a one byte length field for the vendor string, which should be 4 bytes long.
should fix #972

opusenc: correct malformed opus comments

---

doc/build_instructions/windows_msvc.md

Remove references to `opusenc.exe`, as it is no longer required after #814.

doc: update windows build instructions for opus file changes

---

buildsystem/HandleCXXOptions.cmake
copying.md
doc/build_instructions/windows_msvc.md
libopenage/error/handlers.cpp
libopenage/error/handlers.h
libopenage/util/fixed_point.h

Hello, this fixes the build on the newest version of VS2017.
I have also documented a few of the problems I have encountered for others.
Also, I enabled multi-processor compilation on MSVC, that makes a significant difference in build times.
This is my first pull request on github, so be gentle. :P
Greetings.

Fix VS2017 build

---

doc/build_instructions/arch_linux.md

Just a small problem I've found while studying the docs and configuring a development environment on my machine. There is currently no `python-jinja2` package in arch's repo, the correct one seems to be `python-jinja` (note that it does install version 2 of the library as required).
More: https://www.archlinux.org/packages/community/any/python-jinja/

doc: fix python-jinja installation instructions for arch linux

---

assets/qml/GeneratorControl.qml
copying.md
libopenage/gui/engine_link.cpp
libopenage/gui/engine_link.h

This is a third attempt to #616. It builds upon #620, #621 and this specific @TheJJ's comment:
> For this issue, and because we have no server part, I think its enough to just add a button that then calls a function where we can do more complicated things in the future. For now, it can just call Engine::stop().

Add quit button

---

README.md

Readme now links to our Liberapay team page instead of directly redirecting people to the donation form.

Link to Liberapay team page.

---

.gitignore
buildsystem/codecompliance/legal.py
buildsystem/modules/FindPython.cmake
copying.md
libopenage/game_control.cpp
libopenage/game_control.h
libopenage/gamestate/resource.h
libopenage/gui/guisys/private/gui_application_impl.cpp
libopenage/gui/guisys/private/gui_event_queue_impl.cpp
libopenage/gui/guisys/private/platforms/context_extraction_cocoa.mm

There are a few things in this pull request:
1. This reapplies the magic commit from #852 to making rendering work again.
2. Qt elements were flickering... they no longer are.
3. Python libraries wasn't being detected automatically. The solution in the commit is terrible but works. This is trying to solve this issue: #994 
4. Fixes a crash when closing the game window using the red x button (again on macs). A deconstructor had this instruction in its method body: [ud2](https://hjlebbink.github.io/x86doc/html/UD2.html)

macOS touch ups

---

buildsystem/codegen.cmake

This means that these generated files are not guaranteed to exist/update.
Which is good, because then cmake will not run the codegen again and again
to try to update the files. They are not updated if their content does not change,
because that would cause project rebuilds even though there's no reason
for that rebuild (the file would just be touched).

buildsystem: register generated files as byproducts

---

openage/convert/main.py
openage/game/main.py

A while ago, caching of the selected asset conversion source dir was added (#921). This required accessing the config folder, so `convert_assets` was changed to take the `root` directory instead of the `assets` directory. This worked from the game, to the codepath for standalone conversion was not changed due to oversight, so that errors occurred because `assets/assets/converted` and `assets/cfg` didn't exist.
I changed `convert_assets` back to taking the `assets` directory and pass in the cached source directory path from `game.main`, since caching that is pointless for standalone conversion.

convert: fix asset path in standalone conversion

---

libopenage/gui/integration/private/gui_filled_texture_handles.cpp

Gets rid of a compiler warning.

gui: remove unsused lambda captures

---

buildsystem/cythonize.py

We might use more processes than the cpu has cores, but that should be fine.

buildsystem: parallel cythonization

---

copying.md
openage/convert/driver.py
openage/convert/game_versions.py
openage/convert/main.py

With these modifications the converter will only use the `foo_x1_p1.bar` files with patched versions of AoE2.
The result looks fully functional, i.e. I can run `run` and see a game screen.

Add support for unpatched Age of Empires 2: The Conquerors

---

buildsystem/check_py_file_list.py
buildsystem/cythonize.py
buildsystem/pxdgen.py

e.g.
Local git repo is located at: /home/userA/workspace/openage
/home/userA/workspace is a symlink to /mnt/data/workspace
Before /mnt/data/workspace/openage/run.py was compared with /home/userA/workspace/openage/run.py and therefore not recognized as the same file.
Now actual and listed are transformed to the canonical name

This change allows the openage git repository checkout to be located in a directory that is a symlink

---

libopenage/gamestate/resource.h
libopenage/gamestate/score.h
libopenage/unit/ability.h
libopenage/unit/attribute.h
libopenage/unit/command.h

newer gcc spams us with warnings about this.

engine: remove usage of deprecated std::hash::result_type

---

buildsystem/HandlePythonOptions.cmake
copying.md

Support for building openage under a virtualenv. Issue #715

Added work around getsitepackages Issue #715

---

.kevin
CMakeLists.txt
libopenage/console/draw.cpp
libopenage/renderer/font/font.cpp
libopenage/renderer/opengl/buffer.cpp
libopenage/renderer/opengl/buffer.h
libopenage/renderer/shader_program.h
openage/cvar/config_file.py

This fixes a bug where `EXTRA_FLAGS` were not printed in the configuration overview. 
Also, we now have a second arch build with clang, and `-Werror` is turned on for all builds.
The open project configuration for kevin on `ci.sft.mx`  has already been adapted.
Fixes for the remaining warnings are included.

More CI variety

---

libopenage/event/demo/gui.cpp

A wrongly placed `#endif` caused some trouble when building without ncurses.

Fix: builds failed if libncurses was missing

---

libopenage/event/eventstore.h
libopenage/renderer/opengl/context.cpp
libopenage/renderer/resources/mesh_data.cpp

Add missing include directives that caused compile errors locally.
This should not affect other platforms.

libopenage: add missing include directives

---

copying.md
openage/convert/main.py

The logic here is that there might be a Wine bug preventing the game
from fully installing (and thus having the registry key installed), but
the assets are there. This was the case for me and thought it might not
be that rare and worth trying to work around.
The actual Wine bug was that Steam was trying to keep installing MSVC
forever in a loop, at each startup attempt.

Try to use Steam path.

---

openage/codegen/codegen.py

When a Python package which has no `__init__.py` is imported during codegen,
the codegen dependency detector crashed because that package's `__file__`
member is `None` instead of `str`.
With this pull request, that edge case is detected.
Bug encountered on Arch Linux with the module `mpl_toolkits` (see the below error log).
I'm not sure why exactly a package like `mpl_toolkits` (part of `python-matplotlib`) was imported in the first place, which may be a bug in itself, and why that package doesn't have a `__init__.py` (which may be a bug in that package), but this fix is useful in any case.
```
./configure is a convenience script:
it creates the build directory,  symlinks it,
and invokes cmake for an out-of-source build.
Nobody is stopping you from skipping ./configure and our Makefile, …
```

Fix codegen error during cmake/configure phase

---

libopenage/renderer/opengl/buffer.cpp
libopenage/renderer/opengl/context.cpp
libopenage/renderer/opengl/context.h
libopenage/renderer/opengl/framebuffer.cpp
libopenage/renderer/opengl/geometry.cpp
libopenage/renderer/opengl/renderer.cpp
libopenage/renderer/opengl/shader.cpp
libopenage/renderer/opengl/shader_program.cpp
libopenage/renderer/opengl/simple_object.cpp
libopenage/renderer/resources/mesh_data.cpp
libopenage/renderer/resources/texture_data.cpp
libopenage/renderer/resources/texture_data.h
libopenage/renderer/resources/texture_info.cpp
libopenage/renderer/resources/texture_subinfo.h
libopenage/renderer/tests.cpp
libopenage/renderer/text.cpp
libopenage/renderer/texture.cpp
libopenage/renderer/texture.h
libopenage/renderer/texture_array.cpp
libopenage/renderer/texture_array.h
libopenage/renderer/window.cpp
libopenage/renderer/window.h

Fixes #1058 . Also applies some good practice fixes from clang-tidy.

renderer: fix usage of optional and misc

---

doc/building.md
libopenage/CMakeLists.txt

This solves the issue of automoc not being able to parse compact namespaces in Qt 5.5. This issue is resolved in Qt 5.9. This fixes #1043.

Update Qt version requirement from 5.5 to 5.9

---

openage/convert/opus/opusenc.pyx

This was caused by a new version of Cython, which now enforces... stuff.

convert: fix type error during opus conversion

---

doc/media/terrain.md

Github's new parser understands the spaces at the start of these table rows to be a code block. Moving them to the start of the line fixes the issue; I added `---:` to the header column to right-align these numbers in the rendered document.

doc: fix table formatting in terrain.md.

---

buildsystem/HandleCXXOptions.cmake

This speeds up the linking part because [gold is faster](https://en.wikipedia.org/wiki/Gold_(linker)).
This patch also adds support splitting DWARF information into separate files.

buildsystem: use GNU gold linker by default

---

buildsystem/codegen.cmake

The timefile is problematic: cmake says in the implementation of [`cmMakefileTargetGenerator::WriteMakeRule`](https://github.com/Kitware/CMake/blob/b4ccb6cd32029efa802dfdfa889c75bc16f65cf1/Source/cmMakefileTargetGenerator.cxx#L974-L1006):
```
// For multiple outputs, make the extra ones depend on the first one.
```
-> the first output was the timefile, the extra ones are the generated sources.
But the timefile is touched after the sources were generated. The generated sources depend on the (now newer) timefile, so they need to be rebuilt, i.e. touched. Then the generated ones are newer than the dependent C++ files, causing funny unnecessary rebuilds.
Finally fixes #1075.

buildsystem: fix cyclic dependency on unnecessary timefile

---

buildsystem/pxdgen.py
libopenage/CMakeLists.txt
libopenage/event/demo/main.cpp
libopenage/event/demo/main.h
libopenage/renderer/tests.cpp
libopenage/renderer/tests.h

Summary:
- Improve path handling in `buildsystem/pxdgen.py` that fails to match using `str.startswith`.
- Improve thread library target to use instead of `pthread`. Fixes #1062.
- Decorate the DLL interfaces used by the cython extensions with `OAAPI`, which otherwise cause link errors.

Fix windows build

---

libopenage/pyinterface/exctranslate.h
libopenage/pyinterface/pyobject.cpp
libopenage/pyinterface/pyobject.h

Rearrange the code to generate a single namespace statement in `pyobject.pxd`, currently the only file with two of those. This leads the way to enforce a consistent style on pxd annotations in a header file. Once complete, `pxdgen` can be upgraded to identify potential interfaces to decorate with `OAAPI`.
Includes a few modifications using modern C++ syntax.

PyInterface: Rearrange pyobject pxd annotations

---

CMakeLists.txt
buildsystem/cythonize.py
buildsystem/pxdgen.py
buildsystem/python.cmake
run.py.in

- disallow running `run.py.in` directly
- fix `cleancython` target
- skip creating `__init__.p{xd,y}` in the top-level binary directory

buildsystem: use run.py from the build directory

---

buildsystem/pxdgen.py
buildsystem/python.cmake

Fixes #1093.
Tested with a build directory on a different path.
@TheJJ, please check if this fixes the gentoo build.
Side-note: could that be added to Kevin also?
Edit: added buildsystem logic to [avoid hitting #1095](https://github.com/SFTtech/openage/issues/1095#issuecomment-469499833).

pxdgen: fix `path.relative_to` usage

---

configure
copying.md

Just a quick typo fix in the help of ./configure.

Fixed typo

---

copying.md
openage/CMakeLists.txt
openage/__main__.py
openage/cython_check.pyx

Added an empty cython module to be imported by main when running:
`python3 -m openage [...]`
If the import fails, the parser complains and suggests to compile the project or run the command from the build directory.
There was already an ImportError check in place, which I fused with mine, though I wonder if checking for `config` is already enough. I'm sure there is a less ugly way of doing this.
Also, apparently a similar error message was already implemented, but instead of getting redirected to the argparser, it was printed on screen **before** the python errors (which is why I didn't even see it).

Check if cython modules were built and imported correctly

---

libopenage/coord/coord.h.template
libopenage/datastructure/constexpr_map.h
libopenage/datastructure/tests.cpp

- constexpr_map: complete rewrite using `std::array` and relaxed `constexpr` functions.
- make special members for the coordinate base classes use `default`.

Updating some code using C++17

---

libopenage/CMakeLists.txt

if the linking is declared PUBLIC, e.g. all the python modules that
link against libopenage would link to all of libopenage's dependencies
again. when one of those, e.g. libnyan.so, is updated, the module will be
linked again. this means if e.g. libnyan is updated, all python modules
are relinked. this commit removes this transitive linking, and python
modules won't be rebuilt any more.

buildsystem: no transitive linkage for internally used libraries

---

buildsystem/scripts/EmbedPython.cmake
buildsystem/templates/ForwardVariables.cmake.in
doc/build_instructions/windows_msvc.md
libopenage/CMakeLists.txt

- Fix the installer script to include `nyan.dll` in the package.
- Use `CMAKE_SIZEOF_VOID_P` to choose the python zip file according to the target architecture.
TODO:
- Check if someone uses `ARM64` for Windows. [Python binaries unavailable.](https://www.python.org/ftp/python/3.7.3/).

Fix Windows 64-bit installer package

---

buildsystem/templates/openage.bat.in
doc/troubleshooting.md

This fixes the error we get, when calling python from the PATH. With this we call our shipped Python directly.

Start openage explicitly from shipped Python version

---

doc/build_instructions/windows_msvc.md

Replaced Visual Studio with the lighter buildtools,
added dependencies for nyan,
added flag for downloading nyan automatically,
removed comment for non-working packaging as it's working now

Updated windows build instructions

---

.github/FUNDING.yml

Changes proposed in this request:
- Adds the GitHub sponsors button. Here's an example with playnite:
https://github.com/JosefNemec/Playnite
Info from GitHub on this below:
```
.github/FUNDING.yml shows the community how to support this project. Please see our repository funding links [documentation ](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) for more information on formatting and what is and isn't allowed in this file.
Please note that funding links are currently disabled on this repository. Visit repository settings to enable display of your funding links.
```

Add GitHub sponsor button for liberapay

---

README.md

The freenode badge in the README is currently broken, it reads `404 | badge not found`. This replaces the badge by `chat | on freenode`.

Fix broken freenode badge in README

---

README.md

Old link was not suitable anymore, updated it to `good first issues`-label.

Updating easy tasks link in readme.md

---

assets/qml/BindsHelp.qml
assets/qml/IngameHud.qml
buildsystem/codecompliance/__main__.py
libopenage/engine.cpp
libopenage/engine.h
libopenage/game_control.cpp
libopenage/game_control.h
libopenage/gamestate/generator.cpp
libopenage/gui/actions_list_model.cpp
libopenage/gui/engine_link.cpp
libopenage/gui/game_control_link.cpp
libopenage/gui/game_control_link.h
libopenage/renderer/color.cpp
libopenage/renderer/color.h
libopenage/unit/producer.cpp
libopenage/unit/selection.cpp
libopenage/unit/selection.h
libopenage/unit/unit_type.h
libopenage/util/fps.cpp
libopenage/util/fps.h
libopenage/util/profiler.cpp
openage/convert/gamedata/unit.py

Some small gui improvements. There always have been those small gui things that make the first glance of the game little bit... so:
- Moved the unit info to the qml
- Cleaned the player name and abilty info
- Default debug overlay to invisible
- Slower fps updates so they are readable 
(Health bar is placeholder (next pr))
Edit (simonsan): Closes #611

Gui improvements

---

doc/convert/convert_single_file.md
doc/media/slp-files.md
doc/media/smp-files.md
openage/convert/CMakeLists.txt
openage/convert/gamedata/unit.py
openage/convert/hardcoded/texture.py
openage/convert/singlefile.py
openage/convert/slp.pyx
openage/convert/slp_converter_pool.py
openage/convert/smp.pyx
openage/convert/texture.py

Adds more options to the "singlefile" conversion to support newer game versions and SLPs outside of DRS archives. Specifically:
* New option to convert single SLPs
* Support for SLP 3.0, 4.0X, 4.1 (+ documentation)
* Some preparation for DE2

Enhanced singlefile conversion and support for DE1 formats

---

openage/game/main.py

Fixes a minor error where the previous asset path was read in byte mode which created an error when calling `Path(prev_source_dir_path).is_dir()` because that class expects a string.

Fix reading previous asset location

---

copying.md
libopenage/util/enum.h

Add missing self-reference in overloaded assignment operator.

enum.h: add missing self-reference in assignment operator

---

libopenage/gui/guisys/private/livereload/gui_live_reloader.h

The hashes were defined in qtbase.git 4469e36d7203a55a4e158a50f0e9effc3f2fa3c2

qt: don't define std::hash<QString> for qt >= 5.14

---

Makefile

`all` is a recommended target according to the [GNU make documentation](https://www.gnu.org/software/make/manual/html_node/Standard-Targets.html). Eclipse (and other IDEs so I've heard) like to call `make all` by default to trigger a build, so this should be less of a problem now.
For this project, `all` just runs the `default` target. Nothing special was added.

Add 'make all' target

---

doc/media/smx-files.md

I think that the sprite centre values have to be interpreted as signed (instead of unsigned) integers. For example, `u_vil_female_lumberjack_decayA_x1.smx` has a number of frames for which the sprite centre has negative coordinates.

smx-files.md: Signed ints for sprite centre

---

openage/convert/slp.pyx
openage/convert/smx.pyx

The SLP version is now treated as a string with ASCII decoding when using verbose output.
I also fixed the wrong types for hotspots brought up by #1222.

Correctly display SLP version string

---

.github/workflows/macosx-ci.yml

The DejaVu font in `homebrew-cask-fonts` was renamed. Updating the CI correspondingly.
> Rename DejaVu fonts  [PR#2010](https://github.com/Homebrew/homebrew-cask-fonts/pull/2010)
> Cask includes sans, serif, and mono versions – not only the sans.
https://github.com/Homebrew/homebrew-cask-fonts/commit/e9e8d48f6ee9529422d010fb3ec9e6a455ef9ba0

Fixing MacOSX Workflow

---

copying.md

We are in the year of 2020 now.

Change the copyright year of copying.md

---

buildsystem/modules/FindGPerfTools.cmake
buildsystem/modules/FindInotify.cmake
buildsystem/modules/FindNumpy.cmake
buildsystem/modules/FindOpusfile.cmake

Fixing the warnings due to different naming schemes in the `find_package`-commands and the `find_package_handle_standard_args`.
>The package name passed to `find_package_handle_standard_args` (<CMake module name>) does not match the name of the calling package (<CMake module name>).  This can lead to problems in calling code that expects `find_package` result variables (e.g., `_FOUND`) to follow a certain pattern.

Fix CMake warnings

---

.gitignore
CMakeLists.txt
buildsystem/modules/FindPython.cmake
buildsystem/scripts/EmbedPython.cmake
buildsystem/scripts/EmbedWinDependencies.cmake
doc/building.md

Early testing for pulling in CMake 3.12 as Minimum dependency and using Python3.cmake instead of our own FindPython implementation
Fixes #1225

Buildsystem updated to FindPython3.cmake

---

configure
libopenage/log/file_logsink.cpp
libopenage/rng/rng.cpp
libopenage/rng/rng.h

buildsystem: Fix CXX aliases for different clang-versions
Clang-10 bugfix: error: implicit conversion from 'uint64_t' (aka 'unsigned long') to 'double' changes value from 18446744073709551615 to 18446744073709551616
Clang-10 bugfix: operator '?:' has lower precedence than '|'; '|' will be evaluated first

Fix Clang-10 warnings & fix configure script

---

buildsystem/compilepy.py
etc/pylintrc
kevinfile
libopenage/renderer/vulkan/render_target.h
libopenage/util/hash.h
openage/cabextract/cab.py
openage/convert/main.py
openage/util/files.py

[Kevin](https://github.com/SFTtech/kevin) builds are migrated from within a KVM VM to a podman container within a KVM VM.

kevin: migration for new build host

---

copying.md
libopenage/datastructure/concurrent_queue.h
libopenage/datastructure/tests.cpp
libopenage/datastructure/tests.h
openage/testing/testlist.py

Thought this might be useful...
Test with `make test` -- 1 issue (my email is not in copying.md)

Make ConcurrentQueue support both copy-constructible and move-constructible elements

---

openage/convert/processor/conversion/aoc/processor.py
openage/convert/tool/driver.py
openage/convert/value_object/read/media/blendomatic.py
openage/convert/value_object/read/media/datfile/empiresdat.py

The blendomatic reader now uses an entry from the .dat file for the number of blend modes it has to read. Previously it used the information in the header which defined an incorrect size. The .dat file entry is unique to SWGB and its purpose was unknown before. According to @withmorten, the blend mode count that is read is probably hardcoded and not read from the .dat, so we cannot test whether the entry is the actual blend mode count. But if it works... ¯\\\_(ツ)_/¯

Read number of SWGB blend modes from .dat file

---

doc/building.md

I was told this system doesn't exist anymore, so this pull request removes a part of the docs that mentioned it.

doc/building.md: remove mention of the obsolete simple buildsystem

---

doc/build_instructions/arch_linux.md
doc/build_instructions/debian.md
doc/build_instructions/fedora.md
doc/build_instructions/freebsd.md
doc/build_instructions/opensuse_13.2.md
doc/build_instructions/opensuse_tumbleweed.md
doc/build_instructions/os_x_10.14_mojave.md
doc/build_instructions/ubuntu.md
doc/build_instructions/windows_msvc.md
doc/building.md
openage/__init__.py

Reverts SFTtech/openage#1283
hehe, we still have `PIL` code, which we either have to remove, or keep pillow as dependency. I think having `PIL.Image` is quite handy.

Revert "Remove pillow from dependencies"

---

openage/convert/main.py
openage/convert/service/init/conversion_required.py
openage/convert/tool/subtool/acquire_sourcedir.py
openage/game/main.py

Since the asset format change detection was deactivated in #1151, the converter would no longer convert any assets by default. The reason for this is that the requirement for conversion was built into the change detection mechanism. (This should be fixed once we have a proper change detection again)
As a quick fix I added a prompt that asks the user if they want to convert the assets, so new users are not as confused.

Add option for asset conversion without --force

---

copying.md
openage/__main__.py

As newcomer to this project I don't fully understand the need for having two separate devmode overrides, so I didn't touch that logic.
Nevertheless, it seems to me that manually enforcing mutual exclusion of `--devmode` and `--no-devmode` might be error prone and could be handled entirely within argparse.
Downside of this change is that we lose custom error string here, but in this case it IMO shouldn't matter that much as these two options are opposite of each other.

make --devmode and --no-devmode mutually exclusive through argparse

---

.github/workflows/macosx-ci.yml
.gitignore
CMakeLists.txt
README.md
doc/build_instructions/opensuse_13.2.md
doc/build_instructions/opensuse_tumbleweed.md
doc/build_instructions/os_x_10.14_mojave.md

pls work
fixes #1295 
closes #1238

update macOS ci config

---

openage/default_dirs.py

Fix typo: `env_var` -> `env_vars`
Resolves #1337

Fix a typo in python code

---

copying.md
openage/convert/entity_object/conversion/converter_object.py

Added a try...catch to `get_member(self, name)` method of `ConverterObject`.

More informative KeyError messages in converter

---

.github/workflows/macosx-ci.yml
doc/code/converter/README.md
doc/code/converter/workflow.md
doc/convert/debugger.md
openage/convert/entity_object/conversion/aoc/genie_civ.py
openage/convert/entity_object/conversion/aoc/genie_tech.py
openage/convert/entity_object/conversion/aoc/genie_unit.py
openage/convert/entity_object/conversion/ror/genie_tech.py
openage/convert/main.py
openage/convert/processor/conversion/aoc/processor.py
openage/convert/processor/conversion/de2/processor.py
openage/convert/processor/conversion/ror/processor.py
openage/convert/processor/conversion/swgbcc/processor.py
openage/convert/service/CMakeLists.txt
openage/convert/service/debug_info.py
openage/convert/tool/driver.py
openage/convert/value_object/read/member_access.py

Implements the current ideas from https://github.com/SFTtech/openage/issues/1343 in a new dubug service.
Extra improvements:
* ~~Use a data definition format for output (probably toml) instead of a pure plaintext dumps~~

Output summary of converter run for debugging

---

CMakeLists.txt
buildsystem/HandlePythonOptions.cmake
copying.md

Prequisite for Linux Flatpak support without ugly hacks.
Signed-off-by: David Heidelberg <david@ixit.cz>

buildsystem: install all files into prefix on Linux

---

cfg/CMakeLists.txt
openage/convert/main.py
openage/game/main.py

Fixes https://github.com/SFTtech/openage/issues/1350
Also adds an explanation for why the engine can't use the new asset formats and exits before starting the game.

Fix running the converter from './run' executable

---

flatpak/eigen.json
flatpak/lol.sfttech.openage.json
flatpak/nyan.json
flatpak/python3-cython.json
flatpak/python3-jinja2.json
flatpak/python3-lz4.json
flatpak/python3-numpy.json
flatpak/python3-pillow.json
flatpak/python3-pkgconfig.json
flatpak/python3-setuptools-scm.json
flatpak/python3-toml.json

Flatpak uses KDE Runtime and SDK (since it has Qt libs).
Wayland has to be disabled due to #1300
There is currently enabled too many permission, when game starts working
properly, it needs to be tightened to required minimum.
Cleanup phase should be implemented in future (for headers and other
stuff which remains after libraries).
Closes: #1050
Signed-off-by: David Heidelberg <david@ixit.cz>

Flatpak support

---

copying.md
doc/build_instructions/os_x_10.14_mojave.md

Bettered the brew installation to avoid  warnings and added the fact one could generate docs. Only figured that out from scouring the docs.
Sorry if this is too little for a pull request. This is my first time contributing, but please do correct me so I learn!

Small improvements in macOS build instructions

---

copying.md
openage/convert/value_object/read/media/smx.pyx

`damage_modifier_2` is 6 bits long, but the bitmask `0x1F` had only 5 bits (contrary to what the comment above it says). This PR fixes that.
This fix is also aligned with the SMX specification (https://github.com/SFTtech/openage/blob/master/doc/media/smx-files.md) in this project. I found this bug and validated the proposed fix when I was implementing my own SMX updater library in Python.

Bugfix: Correct the damage_modifier_2 bitmask

---

openage/convert/value_object/read/media/smx.pyx

Not doing this led (on my machine) to some weird non-deterministic behavior: In a small number of resources, the palette would vary in the first 4 pixels (4to5 compression)

Explicitly initialize integers created via cdef

---

cfg/converter/games/game_editions.toml
openage/convert/service/conversion/internal_name_lookups.py
openage/convert/service/read/gamedata.py
openage/convert/service/read/string_resource.py
openage/convert/tool/driver.py
openage/convert/value_object/read/media/datfile/empiresdat.py
openage/convert/value_object/read/media/datfile/terrain.py

The converter now uses the correct number of terrains for that file --> 42 like in AoC.
Language file support was also streamlined, so that the data conversion is successful. Media conversion still fails because of the non-existent terrain SLP files.

Fix HD Edition's empires_x1 dat file conversion

---

buildsystem/codecompliance/pylint.py
libopenage/error/error.cpp
libopenage/error/handlers.cpp
libopenage/event/eventhandler.h
libopenage/gamestate/old/game_spec.cpp
libopenage/pyinterface/exctranslate_tests.cpp
libopenage/renderer/font/font.h
libopenage/renderer/font/glyph_atlas.cpp
libopenage/util/compiler.h
libopenage/util/enum.h
libopenage/util/hash.h

"if the header is not included, every use of the keyword `typeid`
makes the program ill-formed".

util: include typeinfo header for typeid

---

buildsystem/check_py_file_list.py
buildsystem/codecompliance/__main__.py
buildsystem/codecompliance/authors.py
buildsystem/codecompliance/legal.py
buildsystem/codecompliance/pylint.py
buildsystem/codecompliance/util.py
buildsystem/compilepy.py
buildsystem/cythonize.py
buildsystem/inplacemodules.py
buildsystem/pxdgen.py
doc/ide/vscode.md
etc/pylintrc
openage/cabextract/test.py
openage/codegen/codegen.py
openage/codegen/coord.py
openage/codegen/main.py
openage/convert/entity_object/conversion/aoc/genie_unit.py
openage/convert/entity_object/conversion/stringresource.py
openage/convert/processor/conversion/aoc/civ_subprocessor.py
openage/convert/service/export/opus/demo.py
openage/convert/service/init/version_detect.py
openage/convert/tool/subtool/version_select.py
openage/convert/value_object/init/game_version.py
openage/convert/value_object/read/media/blendomatic.py
openage/util/fslike/directory.py
openage/util/system.py

Our CI now uses a newer version of `pylint` with more complaints. This PR addresses the issues raised.
* Disable pylint code `R0801` (duplicate code check)
* Fix a few missing uppercases for enums
* Add `with` statements where it makes sense
* `autopep8` settings for IDEs

Address pylint >2.7 issues

---

buildsystem/pxdgen.py

In pygments 2.10.0 the whitespace is tagged with Token.Text.Whitespace, which could cause build breaks like https://github.com/duanqn/openage/runs/3383662608?check_suite_focus=true

Fix the condition for pygments 2.10.0

---

libopenage/gui/guisys/public/gui_property_map.cpp
libopenage/main/tests.cpp
libopenage/main/tests.h

1. Add missing header <stdexcept>.
2. Add missing OAAPI macro, which generates `__declspec(dllexport)` / `__declspec(dllimport)` on Windows.

Fix Windows build failures

---

openage/__main__.py
openage/game/main.py

As stated in https://docs.python.org/3/library/os.html#os.add_dll_directory, Python 3.8+ on Windows uses DLL paths added with `os.add_dll_directory`, and the PATH is not used.

Add a Python argparse option to supply additional DLL search paths for Windows 

---

doc/build_instructions/windows_msvc.md

Update Windows build instructions to include the `--add-dll-search-path` option.

Update Windows build instructions

---

openage/convert/tool/subtool/version_select.py

Fixes a regression from https://github.com/SFTtech/openage/pull/1414 where the converter does not exit properly if an unsupported version is found.

Fix check for handling unsupported versions

---

.github/workflows/macosx-ci.yml
copying.md
doc/build_instructions/macos.md

Cask `fonts-dejavu-sans` no longer exists,
the dejavu-sans fonts are now included
in the cask `fonts-dejavu`.
Aslo `brew --cask` is no longer needed with
newer versions of homebrew.
fix #1436

Update macOS instructions

---

buildsystem/modules/FindPython.cmake
copying.md

* Removed old implementation
* Using Cmake Math function
* Bit shifting python versions to create PYTHON_MIN_VERSION_HEX  
This PR Fixes #1438

Re-implemented how PYTHON_MIN_VERSION_HEX is computed

---

shell.nix

I've recently found Nix and it helps a lot in dependency installation and maintenance. I'm an absolute noob but I figured this might help someone else in installing openage. With nix and this file, it's as easy as running `nix-shell`!
I am a noob so please do tell me everything I do wrong. I'm not sure if this is the correct way of making a pull request, for example. Thanks opeange team, keep going, this project is awesome!

Added 'shell.nix'. Was able to compile openage without error (in arch)

---

buildsystem/codecompliance/__main__.py
buildsystem/codecompliance/authors.py
buildsystem/codecompliance/util.py
copying.md
libopenage/event/demo/gui.cpp

build error fixed

---

.github/workflows/macosx-ci.yml
.github/workflows/ubuntu-21.04.yml
.github/workflows/windows-server-2019.yml
.github/workflows/windows-server-2022.yml

Uses the newer checkouts version `actions/checkout@v3`

Update GitHub actions to v3

---

.github/workflows/ubuntu-22.04.yml
README.md
doc/build_instructions/ubuntu.md
docker/devenv/Dockerfile.ubuntu.2204

This PR adds a build on ubuntu 22.04 to the github workflows.
This PR is also evidence that #1474 is solved (I haven't tried to build locally though, only fiddled with the yml files).

Add ubuntu 22.04 to the build pipeline

---

buildsystem/CheckRuntimeDependencies.cmake
buildsystem/HandlePythonOptions.cmake
buildsystem/modules/FindPython.cmake
doc/building.md

Fixes #1481 and improves the code base a bit.
* Check system version for compatibility and don't try to use it if it is too low
* do not search for the system version if `PYTHON_DIR` is set
* Remove a `distutils` deprecation warning
* Let the build script search for `toml` and `lz4` which are required modules

Fix Python search during build

---

doc/media/patterns/slp.hexpat
doc/media/slp-files.md

Pattern file for the [imHex](https://imhex.werwolv.net/) editor @ https://github.com/WerWolv/ImHex
Works for SLPs up until version 3.0 (i.e. formats used before the DE releases). Not really optimized at the moment, but that's something to solve for later ¯\\\_(ツ)_/¯.

`imHex` pattern for SLP files

---

doc/media/patterns/slp.hexpat
doc/media/patterns/slp_v4.hexpat
doc/media/sld-files.md
doc/media/slp-files.md
doc/media/smp-files.md
doc/media/smx-files.md

Fixes the link to the imHex pattern files and adds table of contents to the format specs for better readability.
Also adds a new pattern file for SLP>=v4.0

Clean up graphics documention

---

openage/convert/service/export/interface/visgrep.pyx
openage/convert/service/export/opus/opus.pxd
openage/convert/service/export/png/libpng.pxd
openage/convert/value_object/read/media/slp.pyx
openage/convert/value_object/read/media/smp.pyx
openage/convert/value_object/read/media/smx.pyx
openage/cppinterface/exctranslate.pyx
openage/cppinterface/pyobject.pyx
openage/game/main_cpp.pyx
openage/main/main_cpp.pyx
run.py.in

Cython 3 changes a few things which caused trouble in the builds.

Fix Cython 3 problems

---

.github/workflows/macosx-ci.yml
.github/workflows/windows-server-2019.yml
.github/workflows/windows-server-2022.yml
buildsystem/CheckRuntimeDependencies.cmake
copying.md
doc/build_instructions/arch_linux.md
doc/build_instructions/debian.md
doc/build_instructions/fedora.md
doc/build_instructions/freebsd.md
doc/build_instructions/macos.md
doc/build_instructions/opensuse.md
doc/build_instructions/ubuntu.md
doc/build_instructions/windows_msvc.md
doc/building.md
libopenage/coord/coord.cpp.template
libopenage/coord/coord.h.template
openage/__init__.py
openage/codegen/coord.py
openage/config.py.in
packaging/docker/devenv/Dockerfile.ubuntu.2204
shell.nix

Pretty descriptive title. This closes #1273.

Use Mako instead of Jinja2

---

copying.md
libopenage/main.cpp
libopenage/main.h
openage/game/main.py
openage/game/main_cpp.pyx
openage/main/main.py
openage/main/main_cpp.pyx

Add CLI parameter for running without graphics

---

doc/changelogs/engine/v0.5.0.md

Ready for release :rocket: 
resolves https://github.com/SFTtech/openage/issues/1518

doc: Changelog v0.5.0

---

libopenage/engine/engine.h
libopenage/renderer/opengl/shader_program.cpp

Fixes https://github.com/SFTtech/openage/issues/1556
* Removes pre-processor error when `std::jthread` is not found
* Fixes another weird substitution error in renderer

Fix clang build

---

assets/test/CMakeLists.txt
assets/test/nyan/CMakeLists.txt
assets/test/qml/CMakeLists.txt
libopenage/presenter/presenter.cpp

Fixes https://github.com/SFTtech/openage/issues/1564
The test asset folders should now be correctly picked up by cmake.

Add missing asset directories to CMakeLists

---

copying.md
openage/convert/processor/conversion/aoc/processor.py

In file: processor.py, the comparison of Collection length creates a logical short circuit. The length of a collection is always greater than or equal to zero. So testing that a length is less than zero is always false.
I suggested that the Collection length comparison should be done without creating a logical short circuit. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security. …

Fix an inappropriate test expression to remove a logical short circuit

---

libopenage/util/matrix.h

Fixes https://github.com/SFTtech/openage/issues/1568
The previous version calculated the insertion indices incorrectly but the values were still placed at the correct memory addresses. That's why the tests ran through but `_GLIBCXX_ASSERTIONS` complained.

Fix out of bound access in matrix constructor

---

Makefile

Fixes https://github.com/SFTtech/openage/issues/1571
`main` and `game` were switched in the latest feature release and `game` requires arguments now. `main` has a more "main menu" CLI flow, so using it as the default entry point makes sense.

Let `make run` call `main` sumodule instead of `game`

---

buildsystem/DetectProjectVersion.cmake

Fixes incorrect version number being displayed in source builds.

Allow non-annotated tags from git for setting version

---

doc/media/openage/modpack_definition_file.md
libopenage/gamestate/game.cpp
openage/convert/tool/api_export.py

Improves modpack loading a bit
- Clarify difference between `version` and `versionstr` in modpack info file
- Fix engine modpack export via CLI
- Replace a usage of `std::string::substr()` with a constant string
This is a cherry-picked version of https://github.com/SFTtech/openage/pull/1574 without the changes to the `engine` modpack version.

Modpack load fixes

---

doc/build_instructions/arch_linux.md

Add instructions on how to add `toml11` from the AUR on Arch Linux.

Add AUR instructions for installing `toml11`

---

buildsystem/DetectProjectVersion.cmake

Our buildsystem expects version tags in the format `v1.2.3-4-g00abcdef` (tag + commit distance to tag + commit hash). However, since https://github.com/SFTtech/openage/pull/1576 we call `git describe --tags`. When `HEAD` is tagged, this command only outputs the tag and omits commit distance and commit hash (only `v1.2.3` is returned). This results in a configure failure since our regex cannot match the version format in this case.
This PR switches the version fetch command to `git describe --tags --long`, so that the long format is always used.

Fix version tag regex failure when HEAD is tagged

---

doc/code/converter/architecture_overview.md
doc/code/converter/workflow.md

fixed typos in the architecture and workflow files

doc: Fix typos in converter

---

copying.md
openage/convert/processor/export/media_exporter.py
openage/convert/service/debug_info.py
openage/convert/tool/driver.py

Created debug output for sounds not found on exporting stage and for execution time for each stage
resolve: #1343

Converter debug

---

openage/util/fslike/path.py
openage/util/fslike/union.py

Turns out append modes were not properly checked for unions which made it unusable for writing to files.

Fix append mode not available

---

libopenage/renderer/opengl/context.cpp
libopenage/renderer/opengl/context.h
libopenage/renderer/opengl/framebuffer.cpp
libopenage/renderer/opengl/framebuffer.h
libopenage/renderer/opengl/render_target.cpp
libopenage/renderer/opengl/render_target.h
libopenage/renderer/opengl/renderer.cpp

Changes the default FBO ID from being hardcoded to fetching it every frame for the current context. This is necessary for platforms where the default FBO is not fixed to `0` and changes on a frame-by-frame basis, e.g. when using Wayland.
Fixes https://github.com/SFTtech/openage/issues/1596

Dynamically fetch default FBO

---

copying.md
libopenage/util/fixed_point.h
libopenage/util/fixed_point_test.cpp

- #1543 
- Added `atan2` as a member function to `FixedPoint`
- Added `atan2` function for `FixedPoint` in std namepace
- Added a test case for `atan2`

Add `atan2` to `FixedPoint`

---

assets/shaders/world2d.vert.glsl

Fixes jittery animation when using mirrored angles.

Mirror anchor offset when flipping is active

---

.clang-format

Finnaly let's us auto-format the enclosing bracket on a new line.
Before:
```cpp
this->display_shader->new_mom(
"mass",
1337,
"hide",
false);
```
After:
```cpp
this->display_shader->new_mom(
"mass",
1337,
"hide",
false
);
```

Use block indent for aligning after open brackets

---

copying.md
openage/convert/entity_object/conversion/aoc/genie_unit.py

`make checkall` gets pylint error as follows:
openage/convert/entity_object/conversion/aoc/genie_unit.py:483:31: E0601: Using variable 'head_unit_connection' before assignment (used-before-assignment)
It is caused by an incomplete if-else block, and can be fixed by adding an else-branch raising ValueError.

complete if-else branch to fix pylint error

---

.clang-format

Currently, using `BlockIndent` can reformat other parts of the code to something less readable, e.g.
```cpp
void WorldRenderEntity::update(const uint32_t ref_id,
const curve::Continuous<coord::phys3> &position,
const curve::Segmented<coord::phys_angle_t> &angle,
const std::string animation_path,
const time::time_t time)
```
to
```cpp
void WorldRenderEntity::update(const uint32_t ref_id, const curve::Continuous<coord::phys3> &position, const curve::Segmented<coord::phys_angle_t> &angle, const std::string animation_path, const time::time_t time)
```
This is not really great for readability, so I would switch back to the old style until we or clang-format has a solution for this.

Revert "Merge pull request #1602 from heinezen/clang-format-align"

---

libopenage/util/fixed_point.h
libopenage/util/fixed_point_test.cpp

To add pure fixed-point math functions (issue #1543), I found it would be better add some math constants (issue #1544). So here is a WIP PR which adds first two important constants, E and PI. The solution is as follows.
(1) In "fixed_point.h", I add two staic functions which return E and PI, respectively, referrng to the implementation of the fpm library.
(2) The from_fixedpoint() function is fixed to avoid the situation of narrowing warning/error furing compilation when the fractional_bits  of created FixedPoint constant object is smaller than the predefined one, i.e., 61.
(3) By the way, I also amend the comment doc of safeshift function.
(4) In "fixed_point_test.cpp", I add some tests which utilizes the constants defined in "math_constant.h" for comparison. I also test constant under …

Add math constants corresbonding to `util/math_constants.h` for FixedPoint

---

.github/workflows/macosx-ci.yml
doc/building.md

Python 3.12 removed `distutils` but Cython still requires it for building. Until this is solved, we have to pull `setuptools` (which contains `distutils`) as a dependency on platforms that don't automatically support it.

Add setuptools as conditionl dependency

---

doc/code/curves.md
libopenage/curve/iterator.h
libopenage/curve/queue.h
libopenage/curve/queue_filter_iterator.h
libopenage/curve/tests/container.cpp

Reworks the curve queue to make it more intuitive to use and more efficient in certain situations.
In the original design by @Tomatower , elements in a curved queue are mostly accessed by requesting all elements in a timespan (e.g. all elements between `t1 == 0` and `t2 == 5`). You could then iterate through these elements to process them. `front(t)` or `pop(t)` access (like in "normal" queues) to retrieve/remove the front element at a time `t` was not possible.
However, there are a few problems with this in practice which made the queue unintuitive to use. If the elements are processed one at a time, the requirement for a timespan puts a burden on the calling code to track which time/elements have already been processed. If the queue is shared by multiple callers, this adds a lot of …

Queue curve rework

---

libopenage/renderer/opengl/framebuffer.cpp
libopenage/renderer/opengl/render_pass.cpp
libopenage/renderer/opengl/render_target.cpp
libopenage/renderer/opengl/texture.cpp
libopenage/renderer/opengl/texture_array.cpp
libopenage/renderer/opengl/uniform_buffer.cpp

Logs the creation of several OpenGL objects that were previously silently created.
- Frambuffers
- Render passes
- Render targets
- Textures from data
- Texture arrays
- Uniform buffers

Log creation of OpenGL objects

---

openage/convert/processor/export/media_exporter.py

This should now raise an error when the multi-threaded media export fails instead of deadlocking the converter as seen in https://github.com/SFTtech/openage/issues/1624 .

Raise errors inside multiprocessing thread

---

openage/convert/processor/export/media_exporter.py

Fixes a race condition where the converter tries to log the file info before it has been created.
There was also an issue with getting the file size because the previous method relied on resolving the native path which should be resolved now.
I don't think this fixes the original issue of https://github.com/SFTtech/openage/issues/1624 but we are getting there.

Fix logging in multi-threaded conversion

---

copying.md
openage/cabextract/cabchecksum.pyx
openage/util/struct.py

Fix: typos

---

doc/build_instructions/nix.md
doc/building.md
flake.lock
flake.nix
nix/nyan.nix
nix/openage.nix

Hello,
as discussed on matrix few days ago, I'm proposing this PR to add support for nix.
While possibly not idiomatic, this works and adds also support for nyan.

feat: added flake

---

openage/__main__.py

Should fix a multiprocessing error in macOS.

Add freeze_support() before using multiprocessing

---

doc/code/input/README.md

Currently the bullet points in the [input documentation](https://github.com/SFTtech/openage/blob/master/doc/code/input/README.md) are not rendered correctly, which is annoying. This PR should fix this by removing the whitespace before the bullet points.

Fix Markdown rendering of input system README

---

buildsystem/codecompliance/__main__.py
doc/debug.md
etc/gdb_pretty/__init__.py
etc/gdb_pretty/printers.py
etc/openage.gdbinit
libopenage/gamestate/simulation.cpp

Introduces custom GDB pretty printers. These will make fixed-point values, that were previously very hard to parse, human-readable:
- `curve::Keyframe`
- `time::time_t`
```
(gdb) p current_time
$1 = 2.593s = {raw_value = 169934}
```
- `util::FixedPoint`
```
(gdb) p fp
$1 = 1.16888 = {raw_value = 76604, approx_precision = 5}
```
- `util::Vector`

GDB pretty printers

---

etc/gdb_pretty/printers.py
libopenage/coord/coord.h.template
libopenage/curve/keyframe.h
libopenage/util/fixed_point.h
libopenage/util/vector.h

Depends on https://github.com/SFTtech/openage/pull/1633
This just flattens the parent hierarchy to make the parent invisible and directly show the coordinate values.

Coordinate types pretty print

---

libopenage/input/tests.cpp
libopenage/main/demo/pong/gui.cpp
libopenage/presenter/presenter.cpp
libopenage/renderer/demo/demo_0.cpp
libopenage/renderer/demo/demo_1.cpp
libopenage/renderer/demo/demo_2.cpp
libopenage/renderer/demo/demo_3.cpp
libopenage/renderer/demo/demo_4.cpp
libopenage/renderer/demo/demo_5.cpp
libopenage/renderer/demo/stresstest_0.cpp
libopenage/renderer/opengl/context.h
libopenage/renderer/opengl/window.cpp
libopenage/renderer/opengl/window.h
libopenage/renderer/types.h
libopenage/renderer/window.cpp
libopenage/renderer/window.h

We didn't gave any vsync settings in the Qt renderer previously, so I added them again. There's also a new `window_settings` struct that can be extended with flags or other types of configuration data.
The stresstest for the renderer now runs with unlimited FPS by default. It didn't really go under 60 FPS anymore, so this makes the frame dropoff a bit more obvious for now.

Turn off vsync for renderer stresstest

---

assets/shaders/terrain.vert.glsl
assets/shaders/world2d.vert.glsl
libopenage/renderer/camera/camera.cpp
libopenage/renderer/camera/camera.h
libopenage/renderer/demo/stresstest_0.cpp
libopenage/renderer/opengl/renderer.cpp
libopenage/renderer/opengl/shader_program.cpp
libopenage/renderer/resources/buffer_info.cpp
libopenage/renderer/stages/camera/manager.cpp
libopenage/renderer/stages/world/object.cpp
libopenage/renderer/stages/world/object.h
libopenage/renderer/stages/world/render_stage.cpp

Move the scaling of subtextures (i.e. handling of zoom, animation scaling, etc.) to the world shader.
Camera zoom and viewport size are send via the camera's uniform buffer, so these variables are now requested only once per frame. The world object's have to send an additional `float` as a uniform, but no longer have to calculate the scaling themselves which roughly halves the cycles spent on creating these uniform values.
The PR also fixes a bug in the alignment of uniforms in the uniform buffer that was previously not discovered. Uniforms where not properly aligned to a multiple of their size which resulted in the created buffer being too small and using the wrong offsets. This should now be fixed.

Move subtex scaling to shader

---

.github/workflows/macosx-ci.yml

This forces all macOS Python dependencies to be installed via `pip` and not `homebrew`. The homebrew variants didn't always work, so we have to do this workaround.

Force install pip packages in macOS CI

---

libopenage/input/input_manager.cpp
libopenage/input/tests.cpp
libopenage/presenter/presenter.cpp
libopenage/renderer/opengl/window.cpp
libopenage/renderer/window.cpp
libopenage/renderer/window.h

Fixes the order in which input contexts are searched. The intended order was LIFO (like a stack) but the implemented order was FIFO (like a list).
~~This was a nice opportunity to use `std::views::reverse` from the `ranges` library in C++20 :D~~ Disregard that because clang is too old :(
I also added a separate callback list for mouse move actions to the window because mixing them with mouse button actions can be annoying during debugging. This lead me to discover an error in the input demo where some keybindings were not properly assigned which is now also fixed.

Fix order of processing input contexts

---

libopenage/curve/base_curve.h
libopenage/curve/continuous.h
libopenage/curve/discrete.h
libopenage/curve/discrete_mod.h
libopenage/curve/interpolated.h
libopenage/curve/keyframe.h
libopenage/curve/keyframe_container.h
libopenage/curve/queue.h
libopenage/curve/segmented.h
libopenage/curve/tests/curve_types.cpp

So far, we have used `std::list` as the underlying type for curve containers. Lists are nice because they offer constant time insertions and erasure from anywhere in the data structure and have stable iterators, i.e. changing the list doesn't invaliate the iterators.
However, these properties may not be as important for our applications and `std::vector` could be better for performance under these assumptions:
- As elements in the curve are sorted by simulation time, insertions will like be at the end of the container in normal gameplay situations
- Random access for reading elements is likely used more than insertion/removal
- Copying the curve container, e.g. when passing the curve over thread boundaries, would put the the contigious memory layout of `std::vector` at an advantage over …

Port curve container types to `std::vector`

---

doc/build_instructions/nix.md

Hi there!
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113

docs: update NixOS wiki link

---

openage/__main__.py
openage/convert/processor/export/media_exporter.py
openage/convert/tool/singlefile.py
openage/util/CMakeLists.txt
openage/util/dll.py

Fixes the import errors for the compiled libraries and Python modules on Windows by adding better default search paths. If you build openage from source with the documented instructions, there shouldn't be any Python errors after this PR.
The problem in https://github.com/SFTtech/openage/issues/1644 was that the dependent libraries were no longer found automatically since Python 3.8 and you had to use `--add-dll-search-path` to avoid errors. However, it's not always obvious how this argument should be used. Therefore, openage now sets sane defaults to search for:
- `python.dll`
- `openage.dll`
- `nyan.dll`
Furthermore, it fixes the errors in https://github.com/SFTtech/openage/issues/1624 . These happened because the DLLs are only set *per process*, so subprocesses in `multiprocessing` …

Enhance DLL search on Windows

---

libopenage/main/demo/interactive/interactive.cpp
libopenage/renderer/vulkan/graphics_device.cpp

Some files needed an additional include for `<algorithm>`.

Fix missing imports for gcc 14

---

libopenage/log/message.h
libopenage/util/consteval.h

`util::constexpr_` contains helper functions for the openage logger that should be evaluated at compile-time. However, at least for me, these functions were still evaluated at runtime instead. This created a lot of unnecessary call to these functions, especially `strip_prefix`, when logging messages. The log messages take up a giant amount of resources in the event loop for example, due to the frequent calls to the logger.
Since C++20 can enforce compile-time evaluation with the `consteval` keyword, so I replaced all `constexpr` specifiers in the namespace with that. I also changed the name of the namespace to `util::consteval_` to make this change more clear.

Make `util::constexpr_` consteval

---

openage/convert/entity_object/conversion/aoc/genie_object_container.py
openage/convert/entity_object/conversion/aoc/genie_terrain.py
openage/convert/processor/conversion/aoc/ability_subprocessor.py
openage/convert/processor/conversion/aoc/modpack_subprocessor.py
openage/convert/processor/conversion/aoc/nyan_subprocessor.py
openage/convert/processor/conversion/aoc/pregen_processor.py
openage/convert/processor/conversion/aoc/processor.py
openage/convert/processor/conversion/de1/processor.py
openage/convert/processor/conversion/de2/nyan_subprocessor.py
openage/convert/processor/conversion/de2/processor.py
openage/convert/processor/conversion/hd/processor.py
openage/convert/processor/conversion/ror/nyan_subprocessor.py
openage/convert/processor/conversion/ror/pregen_subprocessor.py
openage/convert/processor/conversion/ror/processor.py
openage/convert/processor/conversion/swgbcc/ability_subprocessor.py
openage/convert/processor/conversion/swgbcc/nyan_subprocessor.py
openage/convert/processor/conversion/swgbcc/pregen_subprocessor.py
openage/convert/processor/conversion/swgbcc/processor.py
openage/convert/service/init/api_export_required.py
openage/convert/service/read/nyan_api_loader.py
openage/convert/tool/api_export.py
openage/convert/value_object/read/media/datfile/lookup_dicts.py

Updates the converter to use the changes introduced in https://github.com/SFTtech/openage/pull/1647

Update converter for nyan API v0.5.0

---

doc/build_instructions/ubuntu.md

Added a note about the Linux Mint problem discussed in the #1601.

docs: Add note about linuxmint issue on ubuntu dependencies

---

doc/convert/convert_single_file.md

Fixes the instructions for using the singlefile converter, i.e. the usage of `--palettes-path`.

doc: Correct usage of `--palettes-path` argument

---

libopenage/renderer/resources/parser/common.cpp
libopenage/renderer/resources/parser/parse_blendmask.cpp
libopenage/renderer/resources/parser/parse_blendtable.cpp
libopenage/renderer/resources/parser/parse_palette.cpp
libopenage/renderer/resources/parser/parse_sprite.cpp
libopenage/renderer/resources/parser/parse_terrain.cpp
libopenage/renderer/resources/parser/parse_texture.cpp
libopenage/util/file.cpp
libopenage/util/strings.cpp
libopenage/util/strings.h

Adds a new dedicated `util::split_newline` function that can handle safe splits.

Remove string splits with `\r` from renderer resource parsers

---

doc/build_instructions/windows_msvc.md

Small fix that changes the recommended entrypoint in the Windows build docs from `game` to `main`. `main` includes a user flow that enables the user to convert assets, while `game` doesn't, so it should be a bit easier for newcomers.

Change recommended entrypoint for Windows build

---

libopenage/gamestate/component/api/idle.h
libopenage/gamestate/component/api/live.h
libopenage/gamestate/component/api/move.h
libopenage/gamestate/component/api/selectable.h
libopenage/gamestate/component/api/turn.h
libopenage/gamestate/component/internal/activity.h
libopenage/gamestate/component/internal/command_queue.h
libopenage/gamestate/component/internal/ownership.h
libopenage/gamestate/component/internal/position.h

Small optimization that labels game simulation components as `final`, so they can't be overriden.

Make component classes `final`

---

copying.md
libopenage/renderer/opengl/renderer.cpp
libopenage/renderer/opengl/shader_data.h
libopenage/renderer/opengl/shader_program.cpp
libopenage/renderer/opengl/uniform_buffer.cpp
libopenage/renderer/opengl/uniform_buffer.h
libopenage/renderer/opengl/uniform_input.cpp
libopenage/renderer/opengl/uniform_input.h
libopenage/renderer/uniform_buffer.h
libopenage/renderer/uniform_input.cpp

Made some similar changes as to what was done on #1683. Hope this is somewhat what you had in mind. 
My first PR ever! =)

Update syntax of GlUniformBuffer to match that of GlUniformInput #1683

---

libopenage/renderer/opengl/shader_program.cpp
libopenage/renderer/opengl/shader_program.h

Fixes a small bug in the storage of the texture to tex unit bindings in the shader program. 
https://github.com/SFTtech/openage/blob/02d324292d9b6410655e1052a311ff315b909372/libopenage/renderer/opengl/shader_program.cpp#L427-L429
The current code (see above) assumes that there always exists a binding from tex unit to texture and the `std::optional` type always contains a value. However, this is not always the case, e.g. when the shader is first initialized and no textures have been bound yet. We also wouldn't need to use `std::optional` then, don't we?

Fix tex unit assignment to `std::optional` type

---

openage/cppinterface/exctranslate.pyx

Closes https://github.com/SFTtech/openage/issues/1696
Comments out `_PyTraceback_Add` until we find a better solution for propagating backtraces to Python from C++. This will make the engine compile with Python 3.13 again.

Deactivate `_PyTraceback_Add`

---

.clang-format
libopenage/console/tests.cpp
libopenage/engine/engine.h
libopenage/error/handlers.cpp
libopenage/error/stackanalyzer.cpp
libopenage/event/demo/gui.cpp
libopenage/event/demo/gui.h
libopenage/event/demo/main.cpp
libopenage/event/demo/physics.cpp
libopenage/log/level.h
libopenage/log/message.h
libopenage/log/stdout_logsink.cpp
libopenage/renderer/color.cpp
libopenage/renderer/gui/guisys/private/opengl_debug_logger.cpp
libopenage/renderer/vulkan/loader.cpp
libopenage/util/compiler.cpp
libopenage/util/fds.cpp
libopenage/util/fds.h
libopenage/util/fslike/directory.cpp
libopenage/util/macro/concat.h
libopenage/util/macro/loop.h
libopenage/util/os.cpp
libopenage/util/pty.h
libopenage/util/strings.h
libopenage/util/subprocess.cpp
libopenage/util/thread_id.cpp
libopenage/versions/versions.cpp

Aligns the clang formatting rules for preprocesser directives with what we already use in the files.

Clang format rule: Indent preprocessor directives

---

libopenage/coord/coord.h.template

We previoulsy had a bunch of clang warnings that looked like this:
```
/home/chantal/repo/libopenage/coord/coord_test.cpp:60:5: warning: ISO C++20 considers use of overloaded operator '!=' (with operand types 'openage::coord::tests::(anonymous namespace)::TestCoordsAbsolute' and 'openage::coord::tests::(anonymous namespace)::TestCoordsAbsolute') to be ambiguous despite there being a unique best viable function with non-reversed arguments [-Wambiguous-reversed-operator]
TESTEQUALS(a0, a1);
^~~~~~~~~~~~~~~~~~
/home/chantal/repo/libopenage/coord/../testing/testing.h:53:25: note: expanded from macro 'TESTEQUALS'
if (test_result_left != (right)) { \
~~~~~~~~~~~~~~~~ ^  ~~~~~~~
/home/chantal/repo/.bin/clang++-debug-Oauto-sanitize-none/libopenage/coord/coord_xy.gen.h:86:17: note: candidate …
```

Make comparisons not ambiguous (fixes clang warnings)

---

copying.md
libopenage/util/file.cpp
libopenage/util/file.h
libopenage/util/fslike/directory.cpp
libopenage/util/fslike/directory.h
libopenage/util/path.cpp
libopenage/util/path.h

Addresses #1540
This is currently a static method in util/path.cpp for creating a temp file, wrapping it in a File object, and returning it. I am planning on doing one for temporary directories later, wrapping it in a Directory object instead. Let me know if you'd like me to wrap both in Path objects instead--I'm not really sure how to do that since Path takes in a fslike shared pointer rather than the file_like one produced by File.

File system api c++: added support for creating temp. files and directories

---

libopenage/util/file.cpp
libopenage/util/file.h
libopenage/util/fslike/directory.cpp

Not sure why the CI checks in https://github.com/SFTtech/openage/pull/1706 didn't catch this but the definition of the functions produced linker errors in my local builds. I have edited the definition, so that this does not happen anymore.

Fix definition of static functions for creating temp files/dirs

---

openage/convert/processor/conversion/aoc/processor.py
openage/convert/processor/conversion/de2/tech_subprocessor.py
openage/convert/processor/conversion/de2/upgrade_attribute_subprocessor.py
openage/convert/processor/conversion/de2/upgrade_resource_subprocessor.py
openage/convert/value_object/conversion/de2/internal_nyan_names.py
openage/convert/value_object/read/genie_structure.py
openage/convert/value_object/read/media/datfile/lookup_dicts.py

Adds support for the new BfG DLC for DE2.
There's currently a bunch of placeholder names because we can still figure them out later.
Fixes https://github.com/SFTtech/openage/issues/1701

Convert Battle for Greece DLC

---

libopenage/datastructure/pairing_heap.h
libopenage/datastructure/tests.cpp
libopenage/event/eventstore.cpp

Continuation of #1707 which was accidentally closed when I deleted my fork of openage

data structure: implement pairing heap without use of shared_ptr

---

copying.md
libopenage/renderer/demo/demo_0.cpp
libopenage/renderer/demo/demo_1.cpp
libopenage/renderer/demo/demo_2.cpp
libopenage/renderer/demo/demo_4.cpp
libopenage/renderer/demo/demo_5.cpp
libopenage/renderer/demo/demo_6.cpp
libopenage/renderer/demo/util.cpp
libopenage/renderer/demo/util.h
libopenage/renderer/opengl/uniform_input.cpp
libopenage/renderer/opengl/uniform_input.h
libopenage/renderer/uniform_input.h

Hi, This is my first PR! Issue resolve #1681 
This PR introduces a virtual is_complete() method to UniformInput, with an override in GlUniformInput to validate that all required uniform values are set. 
I'm currently a bit unsure about the optimal place to call is_complete() in the demos. Here are the options I'm considering:
+ After Creation by `new_uniform_input()`:  Might miss uniforms that are added later using the update() method.
+ After Every `update()`: This could introduce unnecessary overhead, especially if updates occur frequently.
+ Before Rendering: Might not catch updates made inside the rendering loop.
I'm looking forward to any feedback!

 Add is_complete() to UniformInput and Implement Checks in Demos 

---

libopenage/engine/engine.cpp
libopenage/engine/engine.h
libopenage/main.cpp
libopenage/main.h
libopenage/presenter/presenter.cpp
libopenage/presenter/presenter.h
libopenage/renderer/opengl/window.cpp
libopenage/renderer/window.h
openage/game/main.py
openage/game/main_cpp.pyx
openage/main/main.py
openage/main/main_cpp.pyx

Close #1546 
+ Defined window-related startup parameters (size, vsync, mode) in Python for `main` and `game` start modes.
+ Passed these parameters to the `main_arguments` struct by creating a `window_arguments` struct
+ Updated C++ logic to forward parameters along `main.cpp` -> `engine.cpp` -> `presenter.cpp`
+ Implemented Fullscreen, Borderless, Windowed three display model in `libopenage/renderer/opengl/window.cpp`

Add CLI Support for Window Parameters

---

openage/convert/processor/export/texture_merge.pyx
openage/convert/service/export/png/binpack.pxd
openage/convert/service/export/png/binpack.pyx

Improve texture converter performance with Cython
resolve: #1371

Speed up converter texture packing with Cython

---

libopenage/pathfinding/pathfinder.cpp
libopenage/pathfinding/pathfinder.h

change default entry sector value from null

---

libopenage/renderer/opengl/geometry.cpp
libopenage/renderer/opengl/renderer.cpp
libopenage/renderer/opengl/renderer.h

Hey! 👋  resolve #1659
I've made some initial fixes for the bufferless quad VAO issue, but wanted to get some advice before finalizing:
1. I tested my current code and noticed the VAO error was still there but occurred during shader validation in [`GlShaderProgram::use()`](https://github.com/SFTtech/openage/blob/beb894520e552cb6224cdd2f64697b2cf6e4ad8a/libopenage/renderer/opengl/shader_program.cpp#L295C1-L302C3). 
This happens during `program->update_uniforms(in);` before `geom->draw()`; in `GlRenderer::render()`.
3. My current fix is binding the empty VAO in `geometry.cpp`, but I'm wondering:
- Should we bind VAO before shader program validation?
- Or should we handle/modify the validation error check in `GlShaderProgram::use()`?
appreciate your thoughts on the best approach!

Bind empty VAO to bufferless quad rendering

---

.gitignore
copying.md

The nix build step creates an output folder called /result. I've added this to the .gitignore file so that git doesn't try to add generated files/binaries to the source tree.

Add Nix build result folder to gitignore

---

doc/code/curves.md
libopenage/curve/CMakeLists.txt
libopenage/curve/array.cpp
libopenage/curve/array.h
libopenage/curve/base_curve.h
libopenage/curve/container/CMakeLists.txt
libopenage/curve/container/array.cpp
libopenage/curve/container/array.h
libopenage/curve/container/element_wrapper.cpp
libopenage/curve/container/element_wrapper.h
libopenage/curve/container/iterator.cpp
libopenage/curve/container/iterator.h
libopenage/curve/container/map.cpp
libopenage/curve/container/map.h
libopenage/curve/container/map_filter_iterator.cpp
libopenage/curve/container/map_filter_iterator.h
libopenage/curve/container/queue.cpp
libopenage/curve/container/queue.h
libopenage/curve/container/queue_filter_iterator.cpp
libopenage/curve/container/queue_filter_iterator.h
libopenage/curve/discrete.h
libopenage/curve/keyframe.h
libopenage/curve/keyframe_container.h
libopenage/curve/tests/container.cpp
libopenage/curve/tests/curve_types.cpp
libopenage/gamestate/component/api/live.cpp
libopenage/gamestate/component/api/live.h
libopenage/gamestate/component/internal/command_queue.h
libopenage/gamestate/entity_factory.cpp

Array curve

---

doc/build_instructions/windows_msvc.md

doc: fix incorrect fontconfig path in Windows build guide

---

Makefile
buildsystem/codecompliance/__main__.py
buildsystem/codecompliance/clangtidy.py
copying.md
doc/building.md
kevinfile

Addressing the issue in #1060. Added clang-tidy check on files inside "libopenage" directory, focusing on "clang-analyzer", "bugprone", "concurrency", and "performance" issues. @heinezen

Add and Test Clang-tidy

---

.github/PULL_REQUEST_TEMPLATES/pull_request_template.md
Makefile
doc/buildsystem.md
doc/contributing.md
doc/ide/configs/vscode/tasks.json

In https://github.com/SFTtech/openage/pull/1710, we introduced `make checkmerge` which replaced `make checkall` for Ci tests. This was not reflected in some of the documentation, which is now fixed with this PR.

Change mentions of 'checkall' to 'checkmerge'

---

copying.md
libopenage/util/fixed_point.h

As a first-time open source contributor, I decided to try implementing additional fixed-point math operTations that were requested that may be nice to see, specifically the trigonometric operations sin, cos, and tan. I hope my code is sufficient to solve this issue!

Added sin, cos, and tan operations to fixed point implementation

---

etc/gdb_pretty/printers.py

Just importing `gdb` doesn't work anymore in gdb 16 apparently. You have to import `gdb.printing` explictly.

Fix import of `gdb.printing` Python module

---

copying.md
libopenage/util/fixed_point.h
libopenage/util/fixed_point_test.cpp

This implements a pure fixed point square root function per #1543.
Notes:
I've just replaced the existing function with a pure fixed point implementation (can't overload when only return type differs). It should be trivial to make it return an actual FixedPoint instead, but that would requiring updating prior test cases and I wasn't sure if that was okay to do.
There's a small loss in precision depending on the value of `fractional_bits` and the position of the most significant bit: if the integer portion is very large, we won't have as much (absolute) precision. Ideally you would want the `intermediate_type` to be twice the size of `raw_type` to avoid any losses.

Add pure FixedPoint sqrt implementation and tests

---

doc/build_instructions/macos.md

Updated build doc for macos.
In the configuration step for macos "clang" is specified instead of "clang++" which causes the linker to output errors due to clang not automatically linking c++ libraries which clang++ will do.

Fix configuration step for macos

---

Makefile
buildsystem/codegen.cmake
libopenage/CMakeLists.txt

`codegen` is now a reserved name in CMake, so we should rename our own codegen target to something else.
This only affects the target name. The invocation and Python code still uses `codegen` as the name.

Rename `codegen` target to `cppgen`
