buildsystem/cpp.cmake, copying.md
a naive attempt at enabling colors in supporting compilers.
=> cmake: fancy colors for modern compilers

doc/code_style/mom.cpp, doc/code_style/mom.h
The codestyle info files needed some updates, please complain about obscurities.
=> Codestyle updates and simplifications

cpp/unit/action.cpp, cpp/unit/attribute.h, cpp/unit/unit.cpp, cpp/unit/unit.h, cpp/unit/unit_container.h
https://stackoverflow.com/questions/5678049/difference-between-uint-and-unsigned-int
=> use unsigned int instead of nonstandard uint

py/openage/convert/fix_data.py
this fixes the pep8 warning E731
=> convert: don't assign lambda to variable

copying.md, cpp/crossplatform/subprocess.cpp
The call function of module subprocess will not increase var total, so the judgement of "if (total > 0)" will always fail.
=> fix judgement of child errno

py/openage/convert/dataformat/util.py
=> add forgotten line separators in csv output

copying.md
Adding full name for awestin1 per TheJJ's request.
=> Adding full name for awestin1

building.md
purely github web interface pull request
=> doc: building.md: align dependencies column, rename T to M

.mailmap, cpp/coord/phys3.h, cpp/coord/tile.h, cpp/pathfinding/path.h, cpp/util/algorithm.h
* foreach added
* reloacte phys3 hashing to correct file.
=> Foreach for containers and other phys3 hash relocation

.travis.yml
long-wanted change, will hopefully reduce the waiting times for travis.
=> ci: run make checkfull before compiling

py/openage/convert/blendomatic.py, py/openage/convert/drs.py, py/openage/convert/gamedata/empiresdat.py, py/openage/convert/hdlanguagefile.py, py/openage/convert/mediafile.py, py/openage/convert/pefile.py, py/openage/convert/util.py, py/openage/util.py
Probably closes #243 and finally resolves #55.
Implements case insensitive file name fetching for the whole conversion process.
Please test on all plattforms and game versions, especially @dopsi @Almin17 and @SkySkimmer are encouraged to try whether this branch works for them.
@goto-bus-stop, please review the HD support of this, I can't test it because of a lacking installation.
=> Casesensitivity fixes

copying.md, cpp/pathfinding/CMakeLists.txt, cpp/pathfinding/path.cpp, cpp/pathfinding/tests.cpp
Added tests for the basic pathfinding methods.
=> Pathfinding testing #189

.travis.yml
probably speeds up the ci run
i also removed some leftover config sections for coverity.
=> ci caching

cpp/CMakeLists.txt, cpp/datamanager.cpp, cpp/rng/CMakeLists.txt, cpp/rng/global_rng.cpp, cpp/rng/global_rng.h, cpp/rng/rng.cpp, cpp/rng/rng.h, cpp/rng/rng_tests.cpp, cpp/util/misc.cpp, cpp/util/misc.h
It provides an easy and reliable way of reproducible random numbers,
along with platform-independent serialization.
Sanitized and updated version of #191. Thanks @schets !
=> rng: implemented a random number generator

README.md, doc/usage.md
Couldn't find this when trying the game :)
=> Documented usage

README.md
=> Use SVG build status image in README

cpp/unit/action.cpp, cpp/unit/producer.cpp
fix for docks making ground invisible, and ships becoming invisible when moiving
=> visual fixes for dock/ships

README.md, doc/building.md, doc/ideas/ai.md, doc/ideas/gameplay.md, doc/implementation/assets.md, doc/implementation/logger.md, doc/implementation/terrain.md, doc/milestones.md, doc/usage.md
I've improved the docs:
- Fixed a lot of grammar and spelling issues
- Extended `usage.md`
- Clarified the milestones with checkboxes to show how far we are. I'm not really happy with the current milestones order, because it makes it look like we're less far than we are, but I'm not sure how to improve it.
=> Doc improvements

doc/building.md
changed gnu to gcc 
changed llvm to clang
=> Updated building.md

copying.md, cpp/job/tests.cpp
Did the following things:
* `test_simple_jobs` tests the JobManager by giving it 10 jobs in parallel and checking if it succeeds.
* `test_simple_jobs_with_exception` tests by giving JobManager 5 normal jobs and 5 jobs with throw exceptions.
=> Made existing testcases test JobManager with atleast 10 jobs in parallel  #189

libopenage/terrain/terrain.cpp, openage/convert/CMakeLists.txt, openage/convert/__init__.py, openage/convert/changelog.py, openage/convert/driver.py, openage/convert/gamedata/CMakeLists.txt, openage/convert/gamedata/empiresdat.py, openage/convert/gamedata/maps.py, openage/convert/gamedata/terrain.py, openage/convert/gamedata/unit.py, openage/convert/main.py, openage/testing/testlist.py
=> convert: datfile updates

doc/ideas/gameplay.md
=> doc: gameplay ideas restructured and extended

libopenage/renderer/text_renderer.cpp
=> Fix for text renderer causing game crash

libopenage/testing/testing.h, libopenage/util/CMakeLists.txt, libopenage/util/vector.cpp, libopenage/util/vector.h, libopenage/util/vector_test.cpp, openage/testing/testlist.py
I'll need this in my C++ perlin implementation.
TODO:
=> Vector class with arithmetics

libopenage/util/CMakeLists.txt, libopenage/util/matrix.cpp, libopenage/util/matrix.h, libopenage/util/matrix_test.cpp, libopenage/util/vector.h, openage/testing/testlist.py
Some minor fixes for util::vector included.
=> Matrix class with artihmetics

etc/pylintrc, openage/__init__.py, openage/__main__.py, openage/cabextract/cab.py, openage/codegen/codegen.py, openage/config.py.in, openage/convert/changelog.py, openage/testing/main.py, openage/util/bytequeue.py, openage/util/filelike.py, openage/util/struct.py
=> pylint: fix code or suppress false positives for pylint 1.5.1

copying.md, openage/convert/driver.py, openage/convert/main.py
=> Fix HD 4 version detection

copying.md, libopenage/unit/action.cpp
=> Fix dead units receiving damage

openage/convert/driver.py, openage/convert/main.py
=> convert: fixed game_versions no longer being a str

doc/code/convert/convert_single_file.md, openage/__main__.py, openage/convert/CMakeLists.txt, openage/convert/singlefile.py, openage/convert/texture.py, openage/util/fslike/filecollection.py, openage/util/fslike/path.py
simplified the filesystem abstraction api with more default parameters
added script for converting a single file from a drs to a png to aid #389 .
=> filesystem abstraction improvements, single file conversion

.travis.yml
This should pervent that style issues are burried in all the output.
=> ci: let build steps depend on each other

.travis.yml
all builds would succeed otherwise...
=> ci: let travis fail if the build fails

openage/convert/main.py
=> convert: expand environment variables and ~ in asset path

buildsystem/CheckRuntimeDependencies.cmake
=> buildsystem: fix runtime dependency check.

doc/ideas/gameplay.md
=> Fix a typo in ideas/gameplay

libopenage/console/tests.cpp, libopenage/crossplatform/os.cpp, libopenage/crossplatform/pty.h, libopenage/crossplatform/subprocess.cpp, libopenage/util/fds.cpp, libopenage/util/fds.h
Cleaner, fresher form of #207. Won't harm current platforms :)
=> Stub some unused, unimplemented stuff on WIN32 so it can compile

libopenage/generator.cpp
gentlemen let's honor #218 pls
=> generator: use math::PI instead of M_PI

buildsystem/HandlePythonOptions.cmake, buildsystem/modules/FindNumpy.cmake, buildsystem/python.cmake, openage/convert/CMakeLists.txt, openage/convert/slp.pyx
fixed to determine include dirs
closes #483
=> cythonize rgba matrix calculation

libopenage/unit/action.cpp
Relates to the follow-up in https://github.com/SFTtech/openage/issues/364
=> Correct graphic for idle gathering villager carrying zero amount

libopenage/crossplatform/timing.cpp
BAM, C++11!!
http://en.cppreference.com/w/cpp/chrono
=> crossplatform/timing: use C++11 chrono

buildsystem/modules/FindPython.cmake, libopenage/CMakeLists.txt
These are mostly random fixes that I needed to do in order to run cmake on MSYS2.
I hope they don't break anything!
=> Some tweaks for configuring via cmake on MSYS2

copying.md, openage/convert/main.py
Acording to @TheJJ and **revoof** suggestions, moved the expansion a bit further, possibly enabling #425 close.
=> applying asset path expansion in both AGE2DIR var and input path

README.md, assets/shaders/maptexture.frag.glsl, doc/code/convert/README.md, doc/editor/terrain.md, doc/media/gamedata.md, libopenage/engine.cpp, libopenage/input/action.h, libopenage/input/input_context.h, libopenage/input/input_manager.cpp, libopenage/player.cpp, libopenage/player.h, libopenage/unit/action.cpp, libopenage/unit/unit_texture.cpp, openage/convert/gamedata/unit.py
Mainly includes the new reddit link :)
=> Readme and spelling boost

buildsystem/python.cmake, configure
* compiler alias resolution
* depend on all the python files and not the textual list
=> Buildsystem bugfixes

doc/contributing.md
=> Fix spelling

CMakeLists.txt, buildsystem/HandlePythonOptions.cmake, doc/building.md, openage/CMakeLists.txt
depend on a newer cython version.
=> buildsystem: bump cython to 0.23

doc/media_convert.md
=> Added a method to download assets with SteamCMD

libopenage/error/error.h, libopenage/job/job.h, libopenage/job/job_group.h, libopenage/job/job_manager.h, libopenage/job/typed_job_state_base.h, libopenage/texture.cpp, libopenage/unit/producer.cpp, libopenage/unit/unit.cpp
Adding a macro that throws the Error in a form of `ENSURE(cond, message)`.
=> ENSURE macro for the assertions

doc/contributing.md, doc/reverse_engineering/damage.md
How does the damage calculation work?
How can we prevent more people from collaborating?
All this, in one magnificent pull request!
Incredible !!!
=> Documentation for damage calculations

copying.md, libopenage/CMakeLists.txt, libopenage/console/console.cpp, libopenage/engine.cpp, libopenage/engine.h, libopenage/game_control.cpp, libopenage/game_control.h, libopenage/game_renderer.cpp, libopenage/input/CMakeLists.txt, libopenage/input/action.cpp, libopenage/input/action.h, libopenage/input/event.cpp, libopenage/input/event.h, libopenage/input/input_context.cpp, libopenage/input/input_context.h, libopenage/input/input_manager.cpp, libopenage/input/input_manager.h
Started working on the usage of dynamic key bindings #271.
At the moment, it is only a preparsed (no trailing/leading space) String to Event parser and a dynamic modification of the event/action mapping.
=> Dynamic key bindings

openage/convert/main.py
=> convert: Propose install. directory read from wine registry

libopenage/util/CMakeLists.txt
=> Missing source in CMakeLists.txt in libopenage/util

libopenage/unit/producer.cpp, openage/convert/changelog.py, openage/convert/dataformat/exportable.py, openage/convert/dataformat/members.py, openage/convert/driver.py, openage/convert/gamedata/empiresdat.py, openage/convert/gamedata/research.py, openage/convert/gamedata/sound.py, openage/convert/gamedata/tech.py, openage/convert/gamedata/terrain.py, openage/convert/gamedata/unit.py, openage/convert/main.py, openage/util/files.py
=> convert: intel on sounds, techs and units, and version hashing

openage/convert/dataformat/data_formatter.py
fixes the encoding issue https://github.com/SFTtech/openage/issues/568
=> fix encoding error

copying.md, libopenage/gui/guisys/private/platforms/context_extraction_cocoa.mm
=> context_extraction osx patch

README.md
Some info about breaking OS X builds.
=> update readme with info about OS X

copying.md, libopenage/gui/guisys/private/gui_renderer_impl.cpp, libopenage/gui/guisys/private/platforms/context_extraction_cocoa.mm
=> Fix building on OS X

doc/building.md
notify user the game has packaged and exists in Arch User Repository  (AUR).
=> update archlinux section

doc/reverse_engineering/building_placement.md
This might be related to the range for various other tasks (like keeping
chopping etc.), but I haven't tested that yet.
=> doc: Add section about range to keep building

buildsystem/codecompliance/legal.py, copying.md
fixes #561 
Just did it. :smile:
=> check .qml files for legal headers as well

buildsystem/modules/FindPython.cmake, copying.md
Fixed FindPython in CMake - now look at /usr/bin/env python3
=> Added /usr/bin/env python3 to FindPython.cmake

libopenage/engine.h, libopenage/gui/guisys/private/gui_subtree_impl.cpp, libopenage/gui/guisys/private/gui_subtree_impl.h, libopenage/gui/integration/private/gui_filled_texture_handles.h, libopenage/pyinterface/pyobject.cpp, libopenage/pyinterface/pyobject.h, libopenage/terrain/terrain_object.h, libopenage/util/stringformatter.h
=> noexcept annotation for all move constructors/assignment operators

doc/nyan/examples.md, openage/convert/dataformat/members.py, openage/convert/driver.py, openage/convert/gamedata/civ.py
spelling errors and additional docstring info.
edit: before you merge, I can rebase on the current head. just send me a message.
=> doc: fixes spelling errors in comments

copying.md, doc/build_instructions/arch_linux.md, doc/build_instructions/fedora_20_21.md, doc/build_instructions/fedora_22.md, doc/build_instructions/opensuse_13.2.md, doc/build_instructions/opensuse_tumbleweed.md, doc/build_instructions/os_x_10.10_yosemite.md, doc/build_instructions/ubuntu_15.04.md, doc/building.md
Performed as discussed on the related thread.
fixes #549
=> Update build procedure #549

.gitignore, doc/code/gui.md, doc/code/ide.md, libopenage/gui/CMakeLists.txt
Following a suggestion by @TheJJ.
=> Developing with Qt Creator

openage/convert/changelog.py, openage/convert/main.py
small annoyance i just noticed.
=> convert: if the gamespec hash changes, don't show version numbers

buildsystem/codecompliance/__main__.py, buildsystem/codecompliance/cppstyle.py, buildsystem/codecompliance/textfiles.py, buildsystem/codecompliance/util.py, doc/code_style/mom.cpp, libopenage/audio/opus_in_memory_loader.cpp, libopenage/error/backtrace.cpp, libopenage/error/error.h, libopenage/gui/guisys/private/gui_image_provider_impl.cpp, libopenage/gui/guisys/private/livereload/gui_live_reloader.cpp, libopenage/log/test.cpp, libopenage/pyinterface/pyexception.cpp, libopenage/rng/rng.cpp, libopenage/unit/producer.cpp
- Print line number of an issue
- Added missing space issue (detects `){` and `if/for/while(`)
- Added extra space issue (detects spaces before `;`)
- Can be extended
> For the current master the `make checkfast` print:
>
> ![screenshot from 2017-01-04 17-06-26](https://cloud.githubusercontent.com/assets/6997990/21647642/c5edcfbe-d2a3-11e6-8b9f-9a048d5dbb74.png)
First the whole file string is searched and if at least an issue is found somewhere, the file is searched line by line (in order to generate proper description with  the line and line number).
Regular expressions and generators are used when possible.
=> Textfiles code compliance improvements

copying.md, doc/media_convert.md
Update appmanifest_221380 to not befoul steam's steamapps/common/ directory
=> Update media_convert appmanifest

.kevin, buildsystem/check_py_file_list.py, buildsystem/codecompliance/pystyle.py, buildsystem/codecompliance/textfiles.py, buildsystem/compilepy.py, buildsystem/cythonize.py, buildsystem/pxdgen.py, openage/cabextract/cab.py, openage/cabextract/lzxdstream.py, openage/convert/dataformat/members.py, openage/convert/gamedata/sound.py, openage/convert/gamedata/terrain.py, openage/convert/gamedata/unit.py, openage/convert/interface/visgrep.py, openage/convert/main.py, openage/convert/slp_converter_pool.py, openage/log/logging.py, openage/util/fslike/path.py, openage/util/fslike/wrapper.py, openage/util/strings.py, openage/util/system.py, openage/util/threading.py
=> make pylint errors go away

libopenage/gamestate/game_spec.cpp, libopenage/job/job_manager.cpp, libopenage/renderer/font/font_manager.cpp
Set verbosity level of spammy messages to `debug` or `spam`.
Also some minor consistency fixes.
=> increase verbosity level of some annoying messages

libopenage/gamestate/CMakeLists.txt, libopenage/gamestate/game_main.h, libopenage/gamestate/market.cpp, libopenage/gamestate/market.h, libopenage/gamestate/resource.cpp, libopenage/gamestate/resource.h
This market resource buy and sell logic (not the building)
- The global base prices
- Calc prices for selling and buying
- Perform buy and sell
Based on [doc/reverse_engineering/market.md#prices](https://github.com/SFTtech/openage/blob/master/doc/reverse_engineering/market.md#prices).
=> Market resource prices

doc/reverse_engineering/unit_stats/unit_stats.md
uargh. that was one annoying vim session.
=> fix formatting in unit stats list

.gitignore, doc/code/gui.md, libopenage/audio/CMakeLists.txt, libopenage/audio/audio_manager.cpp, libopenage/audio/audio_manager.h, libopenage/audio/dynamic_loader.cpp, libopenage/audio/dynamic_resource.cpp, libopenage/audio/error.cpp, libopenage/audio/error.h, libopenage/audio/format.h, libopenage/audio/in_memory_loader.cpp, libopenage/audio/in_memory_resource.cpp, libopenage/audio/opus_dynamic_loader.cpp, libopenage/audio/opus_dynamic_loader.h, libopenage/audio/opus_in_memory_loader.cpp, libopenage/audio/sound.cpp, libopenage/audio/sound.h, libopenage/engine.cpp, libopenage/gamestate/game_spec.cpp
This makes the audio system optional. Currently it is disabled if the init fails.
Fixes #679 
Fixes #654 
Fixes #296 
Fixes #206
=> Make audio optional

libopenage/datastructure/constexpr_map.h, libopenage/datastructure/tests.cpp, libopenage/util/CMakeLists.txt, libopenage/util/math_constants.h, libopenage/util/matrix.h, libopenage/util/quaternion.cpp, libopenage/util/quaternion.h, libopenage/util/quaternion_test.cpp, libopenage/util/vector.h, libopenage/util/vector_test.cpp, openage/testing/testlist.py
Something i did a long time ago...
=> Quaternion

libopenage/game_control.cpp, libopenage/game_control.h, libopenage/gamestate/CMakeLists.txt, libopenage/gamestate/generator.cpp, libopenage/gamestate/player.cpp, libopenage/gamestate/player.h, libopenage/gamestate/population_tracker.cpp, libopenage/gamestate/population_tracker.h, libopenage/gui/game_control_link.cpp, libopenage/gui/game_control_link.h, libopenage/gui/qml/IngameHud.qml, libopenage/gui/resources_list_model.cpp, libopenage/unit/action.cpp, libopenage/unit/action.h, libopenage/unit/attribute.h, libopenage/unit/attributes.cpp, libopenage/unit/attributes.h, libopenage/unit/producer.cpp, libopenage/unit/unit_container.cpp
Can anyone give a hint, how can I bind a variable (player.population) to the population slot on the gui/qml?
=> Population

doc/build_instructions/ubuntu_15.04.md, doc/build_instructions/ubuntu_16.04.md, doc/building.md
=> doc: Ubuntu 16.04 requirement

libopenage/gamestate/generator.cpp, libopenage/util/math_constants.h, libopenage/util/quaternion.h
Added tau.
I think @mic-e approves ([math.py#L12](https://github.com/SFTtech/openage/blob/master/openage/util/math.py#L12))
=> Bug fix: Missing tau

copying.md, libopenage/rng/rng.cpp, libopenage/util/CMakeLists.txt, libopenage/util/hash.cpp, libopenage/util/hash.h, libopenage/util/hash_test.cpp, libopenage/util/misc.h, libopenage/util/misc_test.cpp, openage/testing/testlist.py
This is my attempt on #670.
I want to know if I'm doing something incorrectly, I'm fairly new to programming. Later I'll implement some tests.
I implemented myself the siphash algorithm by looking into [the paper](https://131002.net/siphash/siphash.pdf), maybe you instead want to use an existing implementation?
I don't know how to handle the key for Siphash, that key should be always the same one. I think it should be on rng.h and change the value to something random (now I'm using the default key described on the paper). 
As far as I can see, Murmurhash was only used for seeding the RNG, I don't understand how the attack described in [the article](https://emboss.github.io/blog/2012/12/14/breaking-murmur-hash-flooding-dos-reloaded/) affects the RNG.
=> Implement siphash

libopenage/gamestate/resource.cpp, libopenage/util/path.cpp
=> Smallfixes

libopenage/util/fslike/directory.cpp
`utimenstat()` interprets nullptr as "use current time", so I used POSIX `clock_gettime()` to grab current time.
Apparently [`utimes()` can be used instead of `utimensat()`](https://github.com/mpartel/bindfs/issues/6#issuecomment-42538754), we just needed to convert timespec into a timeval.
Fixed the `st_mtim` problem also. We wanted a "modified timestamp" of type `struct timespec`. [`st_mtimespec` should do the trick](https://gist.github.com/Birch-san/ebca41072b8ade2be0bfbc18b110fb94#file-stat_2_sierra-txt-L79).
Fixes #768
=> introduce Mac-specific shims for `utimenstat()` and for `stat.st_mtim`

buildsystem/codecompliance/textfiles.py, doc/project_structure.md, libopenage/engine.h, libopenage/pyinterface/pyobject_tests.cpp
basically PR #731, but Btjones711 did not continue.
=> check for asdf in codecompliance

buildsystem/HandlePythonOptions.cmake
As seen in discussion in https://github.com/SFTtech/openage/issues/792
=> Update required Cython version to 0.25

doc/media/blendomatic.md
Thanks to @aap for the discovery :)
=> doc: add blending mask lookup table

openage/testing/main.py
When running tests, like ```util::tests::constinit_vector``` only one test is run. 
This enables to say run test ```util::tests``` to run all tests prefixed with ```util::tests```: 
```
util::tests::constinit_vector
util::tests::enum_
util::tests::init
util::tests::matrix
util::tests::quaternion
util::tests::vector
util::tests::siphash
util::tests::array_conversion
```
This makes testing one module much more convenient.
=> Prefix-matching for tests

copying.md, libopenage/renderer/color.cpp, libopenage/renderer/color.h
-remove copy constructor and assignment operator(default ones are fine)
-change operator!= to use operator==
=> renderer/color: cleanup

openage/testing/main.py, openage/testing/testlist.py
=> testing: fix copyright year and wrong logic

openage/log/logging.py
@castilma please test now, should be fixed.
=> fix python loglvls

libopenage/game_control.cpp, libopenage/gamestate/CMakeLists.txt, libopenage/gamestate/game_main.cpp, libopenage/gamestate/game_main.h, libopenage/gamestate/game_save.cpp, libopenage/gamestate/generator.cpp, libopenage/gamestate/player.cpp, libopenage/gamestate/player.h, libopenage/gamestate/resource.cpp, libopenage/gamestate/resource.h, libopenage/gamestate/score.cpp, libopenage/gamestate/score.h, libopenage/gamestate/team.cpp, libopenage/gamestate/team.h, libopenage/unit/action.cpp, libopenage/unit/action.h, libopenage/unit/producer.cpp, libopenage/unit/unit_type.h
=> Score & Unit lifecycle

copying.md, libopenage/engine.cpp, libopenage/input/input_manager.cpp, libopenage/input/input_manager.h
Superseeds #838.
I did some style improvements and made the build work on clang.
=> Implemented mouse controlled game window movement

libopenage/coord/phys3.cpp, libopenage/pathfinding/a_star.cpp, libopenage/pathfinding/heuristics.cpp, libopenage/pathfinding/heuristics.h, libopenage/pathfinding/path.cpp, libopenage/pathfinding/path.h
Some stuff I stumbled across recently during another project
- Faster euclidean distance ([explained here](http://akritasak.blogspot.gr/2017/05/c-euclidean-distance-variations.html))
- Squared euclidean distance (for feature use)
=> Euclidean distance optimization

doc/media_convert.md
=> doc: add hint about restarting steam

libopenage/game_control.cpp, libopenage/unit/action.cpp, libopenage/unit/action.h, libopenage/unit/command.h, libopenage/unit/unit.cpp
Gatherers stop responding to commands after collecting 10 resources and not having a dropsite.
=> fix units getting stuck when dropsite isnt found

copying.md, openage/util/CMakeLists.txt, openage/util/profiler.py
Rebased and squashed resubmit of #854.
Documentation for this should be done in #815.
Fixes #826.
=> util: added python profiling helper class

README.md, doc/media_convert.md, doc/troubleshooting.md
Made a troubleshooting guide for questions that were asked all the time.
=> Troubleshooting Guide

README.md, doc/status.md
=> readme: add contact table at the top

doc/build_instructions/gentoo.md, doc/building.md
(not to mention this was the first distro to have packaged openage...)
=> doc/building: add gentoo

copying.md, libopenage/shader/program.cpp
=> Update C-style cast to static_cast in program.cpp

doc/reverse_engineering/game_mechanics/selection.md
Some stuff about selecting units that seems obvious at first, but was actually a bit more complex.
=> doc: Selection mechanics

openage/util/fslike/test.py
Fixes #876.
If we're on a caseignoring filesystem already, we can't assume that other-case files aren't found.
=> fslike: fix caseignoringdir-test for caseignoring filesystems

doc/build_instructions/arch_linux.md, doc/build_instructions/fedora_20_21.md, doc/build_instructions/fedora_22.md, doc/build_instructions/freebsd.md, doc/build_instructions/opensuse_13.2.md, doc/build_instructions/opensuse_tumbleweed.md, doc/build_instructions/os_x_10.10_yosemite.md, doc/build_instructions/ubuntu_16.04.md, doc/build_instructions/windows_msvc.md, doc/building.md, libopenage/CMakeLists.txt, libopenage/engine.cpp, libopenage/screenshot.cpp, libopenage/screenshot.h
\<rant\> libpng's doc is ugly! the api isn't really documented. there is only a list of all functions and a walkthrough. but I miss an explanation for every function, what it does, what the arguments are and what is returned. \</rant\>
this uses directly libpng to create the screenshot. it strips the alpha channel and does the encoding in another thread. (well, when I'm finished)
note to self: I need to learn how to use shared_ptr and unique_ptr. somehow I get unreadable build errors, when I try to use them...
=> Use directly libpng to create screenshots.

doc/convert/convert_single_file.md, doc/convert/interactive.md, openage/__main__.py, openage/assets.py, openage/convert/main.py, openage/convert/singlefile.py, openage/convert/texture.py, openage/cvar/location.py, openage/game/main.py
Fixes #853.
Also fixes a bug introduced by cdd3bf61adc84239a59925a823411edcbc13e1b8, which didn't update the `get_palette` call of the interactive browser.
=> convert: introduce interactive conversion shell

libopenage/gamestate/player.cpp, libopenage/gamestate/player.h, libopenage/unit/CMakeLists.txt, libopenage/unit/ability.cpp, libopenage/unit/ability.h, libopenage/unit/action.cpp, libopenage/unit/action.h, libopenage/unit/attribute.h, libopenage/unit/command.cpp, libopenage/unit/command.h, libopenage/unit/producer.cpp, libopenage/unit/research.cpp, libopenage/unit/research.h, libopenage/unit/selection.cpp, libopenage/unit/selection.h, libopenage/unit/unit.h, libopenage/unit/unit_texture.cpp, libopenage/unit/unit_texture.h, libopenage/unit/unit_type.cpp, libopenage/unit/unit_type.h
Classes
- **ResearchType** immutable (contains the name, cost, patch ...)
- will be extented by **NyanResearchType**
- **Research** muttable (is active, is completed ...)
- **ResearchAbility** and **ResearchAction**
Note: Support for repeating research
=> Research (aka Technologies)

libopenage/engine.cpp
fixes #871.
this is my fastest pr so far
=> fix scrolling without focus

README.md
=> Include other Genie Engine games in Readme

doc/build_instructions/fedora.md, doc/build_instructions/fedora_20_21.md, doc/building.md
=> Consolidate fedora build instructions into a single document

cfg/.gitignore, openage/convert/main.py, openage/game/main.py
=> Remember previous asset location

copying.md, doc/build_instructions/debian.md
Not using pip3 and incorporated the dependency in the apt-get line
=> Debian Sid Build Instructions

libopenage/gamestate/game_spec.cpp, libopenage/unit/producer.cpp, libopenage/unit/unit_texture.cpp, openage/convert/dataformat/exportable.py, openage/convert/dataformat/member_access.py, openage/convert/dataformat/members.py, openage/convert/game_versions.py, openage/convert/gamedata/civ.py, openage/convert/gamedata/empiresdat.py, openage/convert/gamedata/graphic.py, openage/convert/gamedata/maps.py, openage/convert/gamedata/playercolor.py, openage/convert/gamedata/research.py, openage/convert/gamedata/sound.py, openage/convert/gamedata/tech.py, openage/convert/gamedata/terrain.py, openage/convert/gamedata/unit.py
Aims to add support for all Genie Engine games to the converter.
=> Convert data for all Genie Engine games

buildsystem/CheckCompilerFeatures.cmake
Checked features:
- nested namespaces
- structured bindings
=> Require C++ compiler to support C++17 features

doc/ideas/gameplay.md
Also removed a bunch of unnecessary periods
=> [IDEAS] Proposal to allow using wood forests for sneak attacks.

doc/ideas/editor/README.md, doc/ideas/editor/multiplayer.md, doc/ideas/gameplay.md
Most of these are not mine. I've stumbled on them during the year while browsing the aoe2 subreddit, so credits go to the community there.
* [Give resources of resigning players to allies](https://www.reddit.com/r/aoe2/comments/7c82wb/what_are_your_thoughts_on_automatically_making/)
* [Wonders' cost scale with pop cap and player number](https://www.reddit.com/r/aoe2/comments/7hos1r/would_wonders_be_fun_if_they_were_more_expensive/)
* Barbarian Invasion: A fun custom game mode where a few technologically advanced players defend against a lot of low tech players. Inspired by [Romans vs. Barbarians](https://www.youtube.com/watch?v=o35ceXEvV5Q) and a Cultures: Northland map.
* [Phantom mode](https://www.reddit.com/r/aoe2/comments/72f2ih/is_there_a_phantom_mode_for_aoe2/): Like Trouble in …
=> Feature suggestions

doc/ideas/gameplay.md
=> doc: fix whitespace error

doc/build_instructions/os_x_10.10_yosemite.md
it seems this process has changed, or I'm missing something.
https://caskroom.github.io
=> update Homebrew-Cask installation instruction

buildsystem/HandleCXXOptions.cmake, doc/build_instructions/windows_msvc.md
=> Update MSVC build instructions to answer some FAQs

doc/building.md
=> Link to Debian build instructions

doc/media/slp-files.md, openage/convert/slp.pyx, openage/game/main_cpp.pyx, openage/util/profiler.py
Some minor fixes.
Closes #936.
=> Minor fixes

libopenage/game_control.cpp, libopenage/gamestate/CMakeLists.txt, libopenage/gamestate/cost.cpp, libopenage/gamestate/cost.h, libopenage/gamestate/player.cpp, libopenage/gamestate/player.h, libopenage/gamestate/resource.cpp, libopenage/gamestate/resource.h, libopenage/unit/ability.cpp, libopenage/unit/action.cpp, libopenage/unit/attribute.h, libopenage/unit/producer.cpp, libopenage/unit/research.h, libopenage/unit/unit.cpp, libopenage/unit/unit_type.cpp, libopenage/unit/unit_type.h, libopenage/util/math_constants.h
- **Buildings**
- **cost** check and deduction
-  **limits** max at single instance, max ever created
- Player keeps track for each unit type the numbers:
- **units have**: active 
- **units had**: active and dead
- **units pending**: being made
- Player **Resource capacity**
- **Storage** attribute
- Dynamic resources (first steps)
- **Resource**: one resource type (e.g wood)
- **Resources**: set of Resource
- **ResourceBoundle**: Resource-Amount pairs (created with a Resources)
- **Resource** **decay** and **gather rate multiplier**
EDIT:
- **Resource generator** attribute
- Tmp logic in idle action
- **ResourceCost** 
- It can be **constant** or **dynamic** (= function of player)
- Used in **UnitType** and **ReseachType**
EDIT:
- **ResourceBundle** operations with bundles from …
=> Buildings limits, Resource capacity and more

doc/reverse_engineering/game_mechanics/market.md
there are some little differences between AoK and AoC
=> further details on trade gold

README.md
because we now have this fancy freedom-respecting donation account :)
=> readme: add money sink button

doc/reverse_engineering/game_mechanics/damage.md
Adds the correct damage formula from the AoE2 Wiki and explains it.
=> doc: Damage formula

libopenage/util/filelike/filelike.h, libopenage/util/filelike/native.cpp, libopenage/util/fslike/directory.cpp, libopenage/util/fslike/directory.h, libopenage/util/fslike/fslike.h, libopenage/util/fslike/python.cpp, libopenage/util/fslike/python.h, libopenage/util/path.cpp, libopenage/util/path.h, openage/util/fslike/abstract.py, openage/util/fslike/cpp.pyx, openage/util/fslike/directory.py, openage/util/fslike/path.py, openage/util/fslike/test.py
should be the missing piece for #749.
=> fslike: add readwrite and append modes for opening files

.kevin
This will speed up our builds considerably.
=> kevin: enable ccache

doc/reverse_engineering/game_mechanics/garrison.md
Info from ZeroEmpires [video and comments](https://www.youtube.com/watch?v=tCBlWAkanPY).
=> doc: number of projectiles per garrisoned unit

buildsystem/cythonize.py
Cython always emits a warning when calling `cythonize`, no matter if the mentioned line is there or not:
```
Please put "# distutils: language=c++" in your .pyx or .pxd file(s)
```
They always bothered me, now they are gone.
=> buildsystem: suppress useless cython warnings

buildsystem/cythonize.py, buildsystem/pxdgen.py, openage/codegen/codegen.py
=> buildsystem: clean up terminal output

openage/convert/interface/visgrep.pyx
I'm fine with getting rid of the warnings for now. Performance optimizations are surely possible, but the overall time spent in visgrep is rather low, so I don't care too much.
Code has been tested, ingame HUD still looks the same.
=> convert: use memoryviews in visgrep

doc/build_instructions/debian.md, doc/build_instructions/fedora.md, doc/build_instructions/freebsd.md, doc/build_instructions/opensuse_13.2.md, doc/build_instructions/opensuse_tumbleweed.md, doc/build_instructions/os_x_10.10_yosemite.md, doc/build_instructions/ubuntu.md, doc/building.md
18.04 should have no problems with outdated packages.
Also includes the changes from #992 for Fedora.
=> Update required Ubuntu version

libopenage/util/constexpr.h
=> util: C++14ize constexpr functions

buildsystem/codecompliance/headerguards.py
=> buildsystem: fix overly specific headerguard regex

libopenage/log/log.cpp, libopenage/log/logsink.cpp, libopenage/log/logsink.h, libopenage/log/logsource.cpp, libopenage/log/message.h, libopenage/util/stringformatter.h
=> Lazy Log Message Formatting (C++ Side)

buildsystem/pxdgen.py, openage/__init__.py, openage/convert/main.py, openage/log/__init__.py, openage/testing/testing.py, openage/util/fslike/abstract.py, openage/util/fslike/path.py
I updated the build VMs yesterday, pylint 2.0.0 learned new things to complain about. 
I fixed things that seemed reasonable, E1101 for Path.mount is reported upstream.
=> fix or ignore pylint findings

libopenage/event/eventqueue.h
=> Remove std::unary_function usage

libopenage/event/demo/gui.cpp, libopenage/event/demo/main.cpp
=> event: remove usage of unistd.h

copying.md, libopenage/game_control.cpp, libopenage/unit/producer.cpp
Rebase #552. Another attempt :)
Also:
=> Fix building placement

buildsystem/check_py_file_list.py, copying.md
Fixes issue https://github.com/SFTtech/openage/issues/1079
=> fix openage directory to represent canonical form

libopenage/renderer/tests.cpp
Fixes click targets in the renderer demo on wide screens and adds some comments.
=> renderer: fix clicking in demo

buildsystem/codecompliance/headerguards.py, libopenage/renderer/sdl_global.cpp, openage/__init__.py, openage/convert/dataformat/generated_file.py, openage/testing/testing.py, openage/util/bytequeue.py, openage/util/filelike/abstract.py, openage/util/fslike/abstract.py
the kevin vm was updated and the newer pylint finds more buh-buhs.
=> Compliance fixes

openage/codegen/codegen.py
this is then safe against symlinks
=> codegen: take the realpath of generated file paths

buildsystem/pxdgen.py, openage/convert/blendomatic.py, openage/convert/main.py, openage/util/fslike/union.py
* if there was a previous dir, don't skip all other proposals
* try to find the Age2HD installation
* don't crash if the previous source dir has vanished
=> convert source directory finding improvements

buildsystem/codegen.cmake
The CMake Makefile generator will now know how to create missing files,
but this is still better than recompiling half the project
when we just touched the root CMakeLists.txt. The reason behind this
is that CMake's make generator will touch each generated output
in order to make sure depending files get built.
CMake introduced this behavior in its codebase with commit
Kitware/CMake@66a9c90c4bb5bf93bd570a423f99486b24b9337d.
I'm not sure why CMake even does this, because if the code generator
actually updates the file, then there's no need to touch it. Otherwise
if the generated file was not updated, the depending files don't need
any rebuild on purpose.
This is an adapted revert of 51ac97d39c0b826c39070c50e1146ea1521cc6b2,
where the timefile is reintroduced, but the outputs are once again …
=> codegen: create generated files as byproducts

doc/media/evolution-openage-gource.md
Hey there, wrote a short instructions file, do you think it's enough like this or is it too short?
=> Added instructions to reproduce 'evolution video'

doc/building.md
Updated the values to the minimum versions given in build process.
=> Updated linux building dependencies in building.md

README.md
I added the technical overview to the readme to give new visitors a fast intro for all that feature requests and wishes.
=> Added new technical overview to README.md

README.md
Added OpenSAGE and it's URL.
2nd try with comma.
=> Add OpenSAGE to the list

README.md, doc/build_instructions/windows_msvc.md, doc/status.md, doc/troubleshooting.md
I've referenced the windows installer in various locations to bring more attention to it for people that want to play around with openage while not wanting to build it for themselves.
=> Added windows installer reference to various locations

doc/architecture.md
Reading the `architecture.md` it was unclear for me if openage will turn into a `online-only` solution with that architecture changes. I clarified it a bit that it is more clear, that openage will also work offline without an internet connection.
=> Clarified logical process of single- and multiplayer architecture

doc/releasing.md
This is mostly what I did yesterday. Makes sense?
=> document releasing process

copying.md, doc/contributing.md
"good first issue" link was broken because of white spaces, this commit simply fixes that.
=> Changed issue label links in contributing.md

README.md
Suggesting some improvements? to the README as part of [HacktoberFEST2019](https://hacktoberfest.digitalocean.com)
=> Minor README improvements?

CMakeLists.txt, buildsystem/DetectProjectVersion.cmake, buildsystem/scripts/EmbedWinDependencies.cmake, buildsystem/scripts/copy_modules.py, buildsystem/templates/ForwardVariables.cmake.in, libopenage/config.cpp.in, openage/config.py.in, packaging/CMakeLists.txt, packaging/CPackOptions.cmake
=> Packaging openage with prebuilt Qt

README.md
Added the status badge of the SFTtech account @ Travis and took out mine.
=> Updating build status badges

copying.md, libopenage/gui/guisys/private/gui_application_impl.cpp
Addresses #1177 
@simonsan @TheJJ That's what I get after this fix and all the errors go away.
It seems fixed... what do you think?
=> Specify OpenGL (not OpenGLES) explicitly

doc/code/renderer/README.md, libopenage/renderer/CMakeLists.txt, libopenage/renderer/opengl/CMakeLists.txt, libopenage/renderer/opengl/render_pass.cpp, libopenage/renderer/opengl/render_pass.h, libopenage/renderer/opengl/renderer.cpp, libopenage/renderer/opengl/renderer.h, libopenage/renderer/renderer.cpp, libopenage/renderer/renderer.h, libopenage/renderer/tests.cpp
Adresses #1054 
Is this enough?
=> Minimise state changes in renderer

copying.md, libopenage/gui/game_control_link.h
=> Fix crash because of missing null-initialization of pointer

doc/convert/convert_single_file.md, doc/media/smp-files.md, doc/media/smx-files.md, openage/convert/CMakeLists.txt, openage/convert/singlefile.py, openage/convert/slp.pyx, openage/convert/smp.pyx, openage/convert/smx.pyx, openage/convert/texture.py
Adds support for SMX files introduced in DE2.
=> SMX file support

doc/media/slp-files.md
I revised the documentation merging it with my own notes and documentation. I had quite a bit of information to add, so the documentation took a bit of an overhaul. You may want to revise my revision with any changes or wording you feel is appropriate.
=> Revised slp-files.md

doc/media/smp-files.md, doc/media/smx-files.md, openage/convert/smp.pyx, openage/convert/smx.pyx
Adds support for SMP damage modifiers of the pixels, including documentation.
=> SMP damage modifier

doc/media/slp-files.md
Documents the newly found display modifier for DE1's decay/4.1 SLPs.
=> SLP 4.1 display modifier

libopenage/config.cpp.in, libopenage/config.h.in, libopenage/engine.cpp, libopenage/gamestate/game_save.cpp, libopenage/versions/CMakeLists.txt, libopenage/versions/compiletime.cpp.in, libopenage/versions/compiletime.h.in, libopenage/versions/versions.cpp, libopenage/versions/versions.h, openage/__init__.py, openage/config.py.in
=> Added version numbers and layout to version output

doc/build_instructions/windows_msvc.md
Good day folks,
Updated the docs with the latest steps I had to follow while building on Windows with MSVC. @simonsan and I spent a good part of our day figuring out all the hurdles I came upon.
Hope this helps new devs. Thank you!
=> Update windows_msvc build docs with info from latest attempts

CMakeLists.txt, buildsystem/modules/FindPython.cmake, libopenage/log/logsink.h
Fixing some errors I encountered while building on msys2/mingw-w64 toolchain.
Fixes #1272
=> Fix build errors on MingW + GCC-10

doc/media/slp-files.md
Short update about the new compressed container SLPs introduced to DE1.
=> SLP v4.2 compression format and header

copying.md, doc/building.md
=> Update build instructions

doc/changelogs/engine/v0.4.1.md
The changelog for the upcoming release.
=> Changelog v0.4.1

doc/build_instructions/arch_linux.md, doc/build_instructions/debian.md, doc/build_instructions/fedora.md, doc/build_instructions/freebsd.md, doc/build_instructions/opensuse_13.2.md, doc/build_instructions/opensuse_tumbleweed.md, doc/build_instructions/os_x_10.14_mojave.md, doc/build_instructions/ubuntu.md, doc/build_instructions/windows_msvc.md, doc/building.md, openage/__init__.py
pillow is not required anymore. We now use libpng for conversion :)
=> Remove pillow from dependencies

doc/reverse_engineering/game_mechanics/rates.md
I hate it when someone doesn't finish saying what they had to say :)
=> Reverse engineering: finish sentence in game_mechanics/rates.md

.mailmap, CMakeLists.txt, buildsystem/HandlePythonOptions.cmake, buildsystem/modules/FindPython.cmake, buildsystem/python.cmake, buildsystem/templates/ForwardVariables.cmake.in, copying.md, openage/convert/service/export/opus/CMakeLists.txt, openage/convert/service/export/png/CMakeLists.txt
=> Cython module library linking

configure
tiny buildsystem improvement :)
=> configure: support any compiler version suffix

CMakeLists.txt, buildsystem/modules/FindPython.cmake
=> buildsystem: prefer system's default python version

libopenage/console/draw.cpp, libopenage/rng/rng.cpp
Fix [C4805](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4805) and C2416.
=> Fix some MSVC compiling issues

.mailmap, copying.md
i now primarily use a different form of this name and email address.
`make checkfast` says this is ok :crossed_fingers:
thanks!
=> fix my name/email address in the mailmap

doc/media/openage/sprite_format_spec.md
Specification for the improved `.sprite` format discussed in #965 .
Some slight changes were made to the definition in the issue, so we should discuss them in this draft. @Vtec234 @TheJJ
=> Sprite format specification

doc/media/openage/modpack_definition_file.md, doc/media/openage/modpacks.md
Documentation on how modpacks work.
Content:
* What's stored in modpacks?
* Modpack definition file
* Distribution and package management
* Licensing
* Naming conventions
=> Modpacks documentation

openage/convert/tool/singlefile.py
=> Add sound support for single media export

doc/media/smx-files.md
Small addition to the SMX docs.
=> doc: Clarify 3rd bit in 'frame_type'

doc/build_instructions/arch_linux.md, doc/build_instructions/debian.md, doc/build_instructions/fedora.md, doc/build_instructions/freebsd.md, doc/build_instructions/opensuse_13.2.md, doc/build_instructions/opensuse_tumbleweed.md, doc/build_instructions/os_x_10.14_mojave.md, doc/build_instructions/ubuntu.md, doc/build_instructions/windows_msvc.md, doc/building.md, doc/media/slp-files.md, openage/convert/value_object/read/media/slp.pyx
Resolves https://github.com/SFTtech/openage/issues/1284
https://pypi.org/project/lz4/ was added to the dependencies @TheJJ . Please update kevin :)
=> SLP v4.2 export

openage/convert/entity_object/export/media_export_request.py, openage/convert/entity_object/export/texture.py, openage/convert/main.py, openage/convert/processor/export/modpack_exporter.py, openage/convert/tool/driver.py, openage/convert/tool/singlefile.py, openage/convert/value_object/read/media/blendomatic.py
This should implement #1290
Once you are satisfied with the code, feel free to squash fixups or let me know and I'll clean it up before merging.
=> set PNG compression optimization level via CLI

README.md, doc/media/evolution-openage-gource.md, doc/milestones.md, openage/__init__.py, packaging/CMakeLists.txt
=> change logo to svg and update domain names

doc/media/openage/modpack_definition_file.md, openage/convert/entity_object/conversion/modpack.py, openage/convert/entity_object/export/formats/modpack_info.py, openage/convert/processor/conversion/aoc/modpack_subprocessor.py, openage/convert/processor/conversion/de2/modpack_subprocessor.py, openage/convert/processor/conversion/ror/modpack_subprocessor.py, openage/convert/processor/conversion/swgbcc/modpack_subprocessor.py, openage/convert/processor/export/modpack_exporter.py
Transfers changes established in https://github.com/SFTtech/openage/pull/1319 to the converter.
A few additional clarifications were added to the specification.
=> Adapt ModpackInfo output to format version 1

.clang-format, doc/code_style/mom.cpp, doc/code_style/mom.h
unfortunately some things can't be configured, yet. but it should cover most cases and be helpful anyway.
=> add clang-format config which approximates our style

buildsystem/codecompliance/__main__.py, buildsystem/codecompliance/cython.py, openage/convert/processor/export/terrain_merge.pyx, openage/convert/processor/export/texture_merge.pyx, openage/convert/service/export/png/binpack.pyx, openage/convert/service/export/png/png_create.pyx, openage/convert/value_object/read/media/slp.pyx, openage/convert/value_object/read/media/smp.pyx, openage/convert/value_object/read/media/smx.pyx
We accidently left this on in https://github.com/SFTtech/openage/pull/1363, so now there is also a compliance check that tests if profiling is deactivated.
=> Fix: Turn Cython profiling off

openage/convert/processor/export/terrain_merge.pyx
Increase AoC and SWGB conversion speed by 400 %.
https://www.youtube.com/watch?v=atuFSv2bLa8&t=78
=> Replace numpy.any() check with manual short-circuit check

openage/convert/main.py, openage/convert/processor/export/media_exporter.py, openage/convert/processor/export/terrain_merge.pyx, openage/convert/processor/export/texture_merge.pyx, openage/convert/service/export/png/binpack.pxd, openage/convert/service/export/png/binpack.pyx, openage/convert/service/export/png/png_create.pyx
Brings several improvements to the speed of media exporting:
* Speedup binpacking with more Cython
* Do terrain tile merging and projection in a single step
* Deactivate functions that were reliant on POSIX (https://github.com/SFTtech/openage/issues/1306)
=> Converter speedup and Windows works again

openage/convert/processor/conversion/aoc/upgrade_attribute_subprocessor.py, openage/convert/processor/conversion/de2/CMakeLists.txt, openage/convert/processor/conversion/de2/ability_subprocessor.py, openage/convert/processor/conversion/de2/civ_subprocessor.py, openage/convert/processor/conversion/de2/nyan_subprocessor.py, openage/convert/value_object/conversion/de2/internal_nyan_names.py, openage/convert/value_object/read/media/datfile/unit.py
DE2 made a few chanes to the dat format
* New attribute `hero_glow_graphic_id`
* Berserk heal rate is now stored in previously unused value `rear_attack_modifier`
* A few new shenanigans with techs and civ boni
=> Adjustments for DE2 50292 update

CMakeLists.txt, libopenage/util/constinit_vector.h, libopenage/util/enum.h
These changes are necessary to compile the code with g++-11.
=> C++ 20 readiness

libopenage/gui/guisys/link/gui_item.h, libopenage/main/tests/gui.cpp, libopenage/pyinterface/functional.h, libopenage/unit/action.cpp, libopenage/unit/producer.cpp
Fixes the deprecation warnings for C++20.
=> Cpp20 compliance

libopenage/util/fixed_point.h
=> Use C++ 20 spaceship operator

openage/convert/tool/interactive.py
Would be nice to have such a function in interactive mode. Works on my computer :P
=> Add a function to save individual SMX files

libopenage/pyinterface/functional.h, libopenage/util/stringformatter.h
openage now builds successfully with GCC-11: https://github.com/duanqn/openage/runs/3708468188
Previous build log: https://github.com/duanqn/openage/actions/runs/1234113009
=> Fix build issues on GCC-11

.mailmap
Found this by Googling my Email-Address. Please remove. :) 
Maybe this is the easiest way to change it?
```
git filter-branch --commit-filter '
if [ "$GIT_COMMITTER_NAME" = "<Old Name>" ];
then
GIT_COMMITTER_NAME="<New Name>";
GIT_AUTHOR_NAME="<New Name>";
GIT_COMMITTER_EMAIL="<New Email>";
GIT_AUTHOR_EMAIL="<New Email>";
git commit-tree "$@";
else
git commit-tree "$@";
fi' HEAD
```
=> Remove clear text email address

doc/troubleshooting.md
This is a guide for a workaround for an issue I came across here #1433  and is hopefully detailed enough such that in case someone comes across this issue they can resolve it easily.  
@heinezen I am tagging you here, since you were the one who responded to my issue.
=> Added troubleshooting entry for SDL2 build error

.github/workflows/macosx-ci.yml, .mailmap, copying.md, doc/building.md, libopenage/CMakeLists.txt
=> macOS: Update build instructions 

README.md
Link https://bintray.com/simonsan/openage-packages/openage-linux-releases doing a `301 HTTP` redirect
=> 301 Wrong content

copying.md, openage/convert/processor/export/media_exporter.py
Resolves #1423 (Exporting media files task).
=> Added progress bar to media_exporter.py

doc/media/sld-files.md, doc/media/smp-files.md, doc/media/smx-files.md, openage/convert/entity_object/export/texture.py, openage/convert/processor/conversion/de2/media_subprocessor.py, openage/convert/processor/export/media_exporter.py, openage/convert/tool/singlefile.py, openage/convert/value_object/read/media/CMakeLists.txt, openage/convert/value_object/read/media/sld.pyx, openage/convert/value_object/read/media/smx.pyx
Documentation for the new SLD format that will be used in some of the later versions of DE2.
Made with help from @RyanTevious, @spriteblood and @simonsan
=> SLD format

doc/media/sld-files.md, openage/convert/entity_object/export/texture.py, openage/convert/processor/export/texture_merge.pyx, openage/convert/service/export/png/binpack.pxd, openage/convert/service/export/png/binpack.pyx, openage/convert/tool/singlefile.py, openage/convert/value_object/read/media/drs.py, openage/convert/value_object/read/media/sld.pyx, openage/convert/value_object/read/media/slp.pyx, openage/convert/value_object/read/media/smp.pyx, openage/convert/value_object/read/media/smx.pyx
Adds new discoveries for the SLD format
* Pixel data reuse from previous frames
* Export individual layers with singlefile converter
=> SLD Format Updates

openage/convert/value_object/read/media/sld.pyx
Small error because a leftover string comparison should be an object comparison.
=> Fix check for SLD layer type

doc/media/sld-files.md, openage/convert/value_object/read/media/sld.pyx
New bit flag discovery in the file by **spriteblood**.
Also contains a few changes to improve readability.
=> SLD Format Updates Part II

buildsystem/pxdgen.py, openage/convert/service/export/png/CMakeLists.txt, openage/convert/service/export/png/libpng.pxd, openage/convert/service/export/png/png_create.pyx, openage/convert/service/export/png/png_tmp_file.pxd, openage/convert/tool/singlefile.py
=> In-memory PNG file creation

openage/cppinterface/exctranslate.pyx
otherwise it fails to compile:
```
/home/chantal/repo/.bin/g++-debug-Oauto-sanitize-none/openage/cppinterface/exctranslate.cpp:1957:16: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
1957 |   __pyx_v_frame->f_lineno = __pyx_v_lineno;
|                ^~
In file included from /usr/include/python3.11/Python.h:42,
from /home/chantal/repo/.bin/g++-debug-Oauto-sanitize-none/openage/cppinterface/exctranslate.cpp:20:
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
22 | typedef struct _frame PyFrameObject;
```
=> cppinterface: use python's internal PyTraceback_Add function

openage/util/observer.py
Small fix in the Python converter.
=> Fix clearing change in `Observable`

doc/media/patterns/sld.hexpat, doc/media/sld-files.md
Continuation of https://github.com/SFTtech/openage/pull/1507 and https://github.com/SFTtech/openage/pull/1508
Fixes a few things in the SLD docs and adds a pattern file for imHex.
=> SLD pattern file for imHex

libopenage/rng/rng.h
Fixes https://github.com/SFTtech/openage/issues/1511
=> Fix missing include for g++-13

copying.md, libopenage/curve/keyframe_container.h, libopenage/datastructure/pairing_heap.h, libopenage/error/error.cpp, libopenage/pyinterface/exctranslate.cpp, libopenage/util/compiler.h, libopenage/util/compress/lzxd.cpp, libopenage/util/csv.cpp, libopenage/util/path.cpp, libopenage/util/strings.cpp
resolves the second half of https://github.com/SFTtech/openage/issues/1514
=> improvement: replace likely macro with C++20 attribute

libopenage/presenter/presenter.cpp, libopenage/renderer/demo/demo_3.cpp, libopenage/renderer/demo/demo_4.cpp, libopenage/renderer/opengl/renderer.cpp, libopenage/renderer/opengl/shader_program.cpp, libopenage/renderer/opengl/uniform_buffer.cpp, libopenage/renderer/resources/CMakeLists.txt, libopenage/renderer/resources/animation/layer_info.cpp, libopenage/renderer/resources/animation/layer_info.h, libopenage/renderer/resources/assets/asset_manager.cpp, libopenage/renderer/resources/frame_timing.cpp, libopenage/renderer/resources/frame_timing.h, libopenage/renderer/resources/terrain/layer_info.cpp, libopenage/renderer/resources/terrain/layer_info.h, libopenage/renderer/stages/screen/screen_renderer.cpp, libopenage/renderer/stages/terrain/terrain_renderer.cpp, libopenage/renderer/stages/world/world_object.cpp, libopenage/renderer/stages/world/world_renderer.cpp
Optimize some of the functions that are called very often.
=> Small renderer optimizations

doc/build_instructions/windows_msvc.md
Very small changes to bring the Windows docs up to date.
=> Update windows build instructions

.github/workflows/macosx-ci.yml, .github/workflows/windows-server-2019.yml, .github/workflows/windows-server-2022.yml, CMakeLists.txt, doc/build_instructions/debian.md, doc/build_instructions/ubuntu.md, doc/building.md, packaging/docker/devenv/Dockerfile.ubuntu.2204
Updates a deprecated command and the windows build instructions.
=> GitHub actions Update

openage/convert/main.py, openage/util/fslike/path.py
Fixes https://github.com/SFTtech/openage/issues/1557
* Raise `IOError` if we get an invalid handle on open
* Skip asset location write if the file cannot be accessed
=> Make asset location cache file write more robust

libopenage/engine/engine.h
Fixes https://github.com/SFTtech/openage/issues/1573
=> Check if clang jthread is joinable before joining

configure, libopenage/engine/engine.cpp
Fixes https://github.com/SFTtech/openage/issues/1569
=> Prevent engine loop from being optimized out in release builds

README.md
For some reason, the time stamp was slightly too late :D
=> Fix timestamp of video in README

libopenage/renderer/opengl/context.cpp
Should fix https://github.com/SFTtech/openage/issues/1596
=> Check OpenGL format correctly on Wayland

.github/PULL_REQUEST_TEMPLATES/pull_request_template.md, .github/PULL_REQUEST_TEMPLATES/release_template.md
Adds pull request templates to the repo.
=> PR templates

openage/__main__.py
This should me the first start easier for everyone.
=> Make 'main' the default entrypoint

doc/changelogs/engine/v0.5.3.md
Small but probably useful update for keeping track of dependency changes.
=> Mention dependencies in changelog

libopenage/main/demo/interactive/interactive.cpp, libopenage/renderer/vulkan/graphics_device.cpp
Followup to #1652 because it slipped by kevin.
=> Fix copyright years.

.github/workflows/macosx-ci.yml
Fixes the macOS CI problem when installing packages.
=> Fix cask install for brew

doc/changelogs/nyan_api/v0.5.0.md, doc/nyan/aoe2_nyan_tree.svg, doc/nyan/aoe2_nyan_tree.uxf, doc/nyan/api_reference/reference_ability.md, doc/nyan/api_reference/reference_util.md
Small update to our internal nyan API to integrate pathfinding.
=> nyan API v0.5.0

doc/build_instructions/macos.md
Remove additional " in configure command
=> Remove additional quotes in build instructions

README.md
=> readme: add kevin badge

doc/build_instructions/windows_msvc.md
This should help those who want to compile vulkan. See also https://github.com/SFTtech/openage/issues/1749
=> Add `vulkan` package to Windows vcpkg install instructions
